PROGRAM MAIN

USE MODEL_PHYSICS_ECMWF_MOD      , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD                       , ONLY : TERAD
USE YOM_YGFL                     , ONLY : TYPE_GFLD
USE PARKIND1                     , ONLY : JPIM     ,JPRB
USE YOMHOOK                      , ONLY : LHOOK,   DR_HOOK

USE YOMCST                       , ONLY : TCST  
USE YOETHF                       , ONLY : TTHF 

USE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD
USE UTIL_TERAD_MOD
USE UTIL_TYPE_GFLD_MOD
USE UTIL_TCST_MOD
USE UTIL_TTHF_MOD

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV
USE STACK_MOD
USE SHUFFLE_MOD
USE DIFF_MOD

IMPLICIT NONE


REAL(KIND=JPRB)       :: PPLDARE
REAL(KIND=JPRB)       :: PPLRG
INTEGER(KIND=JPIM)    :: KSTEP

TYPE(TTHF)                          :: YDTHF
TYPE(TCST)                          :: YDCST
TYPE(TERAD)                         :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE)      :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE) :: YDML_PHY_SLIN
TYPE(TYPE_GFLD)                     :: YGFL

INTEGER(KIND=JPIM)    :: KSMAX 
INTEGER(KIND=JPIM)    :: KLEV 
INTEGER(KIND=JPIM)    :: KSPPN2D
INTEGER(KIND=JPIM)    :: KTRAC 
INTEGER(KIND=JPIM)    :: KIDIA 
INTEGER(KIND=JPIM)    :: KFDIA 
LOGICAL               :: LDSLPHY 
REAL(KIND=JPRB)       :: PTSPHY 
REAL(KIND=JPRB)       :: PVDIFTS
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSCAV(:) 

INTEGER(KIND=JPIM), ALLOCATABLE   :: KBASEC(:,:)        
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBOTSC(:,:)        
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCBOT(:,:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCTOP(:,:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTOPC(:,:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTYPE(:,:)         
LOGICAL           , ALLOCATABLE   :: LDCUM(:,:)         
LOGICAL           , ALLOCATABLE   :: LDLAND(:,:) 
LOGICAL           , ALLOCATABLE   :: LDSC(:,:)          
LOGICAL           , ALLOCATABLE   :: LDSHCV(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAHFS(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAP(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAPH(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAPHM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PARPRC(:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCAPE(:,:)         
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCM1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCUCONVCA(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCQ(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCS(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDISS(:,:,:)       
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDX(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQIF(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQLF(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCL(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCN(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCL(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCN(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGAW(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGEO(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGEOH(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGP2DSPP(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLCRIT_AER(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLITOT(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLRAIN(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLU(:,:,:)         
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDE(:,:,:)       
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDELI(:,:,:,:)   
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFD(:,:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFDDE_RATE(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFU(:,:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFUDE_RATE(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PQHFL(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PQM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PRSUD(:,:,:,:)     
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSNDE(:,:,:,:)     
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCU(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCV(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENC(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENQ(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENT(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENU(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENV(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PUM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PVERVEL(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PVM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PWMEAN(:,:)        

TYPE (STACK) :: YLSTACK
REAL (KIND=JPRB), ALLOCATABLE :: ZSTACK (:,:)

#include "cucalln_mf.intfb.h"

INTEGER (KIND=JPIM), PARAMETER :: ILUN = 77
INTEGER (KIND=JPIM) :: JBLK, JLON

INTEGER(KIND=JPIM)    :: NPROMA1, NGPBLKS1, NPROMA, NGPBLKS
INTEGER (KIND=JPIM) :: ISTACK
LOGICAL :: LLDIFF, LLVERBOSE
CHARACTER(LEN=256) :: CLCASE, CLCASEREF, CLCASEOUT

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MAIN_CUCALLN_MF',0,ZHOOK_HANDLE)


CALL INITOPTIONS 
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CLCASEREF=CLCASE
CALL GETOPTION ("--case-ref", CLCASEREF)
CLCASEOUT = ''
CALL GETOPTION ("--case-out", CLCASEOUT)
ISTACK = 100
CALL GETOPTION ("--stack", ISTACK)
NPROMA = 32
CALL GETOPTION ("--nproma", NPROMA)
NGPBLKS = 1
CALL GETOPTION ("--ngpblks", NGPBLKS)
NGPBLKS1 = 1
CALL GETOPTION ("--ngpblks1", NGPBLKS1)
CALL CHECKOPTIONS

CALL READALL

CALL COPY (YDTHF)
CALL COPY (YDCST)
CALL COPY (YDERAD)
CALL COPY (YDML_PHY_EC)
CALL COPY (YDML_PHY_SLIN)
CALL COPY (YGFL)

IF (LLVERBOSE) WRITE (0, *) " NPROMA = ", NPROMA, " KLEV = ", KLEV, " NGPBLKS = ", NGPBLKS

ALLOCATE (ZSTACK (NPROMA*KLEV*ISTACK, NGPBLKS))

!$acc data present (YDTHF, YDCST, YDERAD, YDML_PHY_SLIN,  YDML_PHY_EC, YGFL) &
!$acc   & copy (LDLAND, PLCRIT_AER, PTM1, PQM1, PUM1, PVM1, PCM1, PLITOT, PVERVEL, PQHFL, PAHFS, &
!$acc   &       PAPHM1, PAP, PAPH, PGEO, PGEOH, PTENT, PTENQ, PTENU, PTENV, PGAW, PCUCONVCA,     &
!$acc   &       PGP2DSPP, PSCAV, PDX, PTENC, PARPRC, KTOPC, KBASEC, KTYPE, KCBOT, KCTOP, KBOTSC, &
!$acc   &       LDCUM, LDSC, LDSHCV, PLU, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, PDIFCQ, PDIFCS,     &
!$acc   &       PFHPCL, PFHPCN, PFPLCL, PFPLCN, PLRAIN, PRSUD, PSTRCU, PSTRCV, PFCQLF, PFCQIF,   &
!$acc   &       PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWMEAN, PDISS) &
!$acc   & create (ZSTACK)


!$acc parallel loop gang private (YLSTACK) vector_length (NPROMA)

!$OMP PARALLEL DO PRIVATE (JLON, KIDIA, KFDIA)
DO JBLK = 1, NGPBLKS

!$acc loop vector private (KIDIA, KFDIA, YLSTACK)
  DO JLON = 1, NPROMA
    
    YLSTACK%L = LOC (ZSTACK (1, JBLK))
    YLSTACK%U = YLSTACK%L + SIZE (ZSTACK, 1) * KIND (ZSTACK)

    KIDIA = JLON
    KFDIA = JLON
    
    CALL CUCALLN_MF (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN,  YDML_PHY_EC, YGFL, &
    & KIDIA, KFDIA, NPROMA, KSMAX, KLEV, PDX(:,JBLK), KSPPN2D, LDLAND(:,JBLK), LDSLPHY, PTSPHY,      &
    & PVDIFTS, PTM1(:,:,JBLK), PQM1(:,:,JBLK), PUM1(:,:,JBLK), PVM1(:,:,JBLK), PLITOT(:,:,JBLK),     &
    & PVERVEL(:,:,JBLK), PQHFL(:,:,JBLK), PAHFS(:,:,JBLK), PAPHM1(:,:,JBLK), PAP(:,:,JBLK),          &
    & PAPH(:,:,JBLK), PGEO(:,:,JBLK),  PGEOH(:,:,JBLK), PGAW(:,JBLK), PCUCONVCA(:,JBLK),             &
    & PGP2DSPP(:,:,JBLK), PTENT(:,:,JBLK), PTENQ(:,:,JBLK), PTENU(:,:,JBLK), PTENV(:,:,JBLK),        &
    & PARPRC(:,JBLK), KTOPC(:,JBLK), KBASEC(:,JBLK), KTYPE(:,JBLK),    KCBOT(:,JBLK), KCTOP(:,JBLK), &
    & KBOTSC(:,JBLK), LDCUM(:,JBLK), LDSC(:,JBLK), LDSHCV(:,JBLK), PLCRIT_AER(:,:,JBLK),             &
    & PLU(:,:,JBLK), PLUDE(:,:,JBLK), PLUDELI(:,:,:,JBLK), PSNDE(:,:,:,JBLK), PMFU(:,:,JBLK),        &
    & PMFD(:,:,JBLK), PDIFCQ(:,:,JBLK), PDIFCS(:,:,JBLK), PFHPCL(:,:,JBLK), PFHPCN(:,:,JBLK),        &
    & PFPLCL(:,:,JBLK), PFPLCN(:,:,JBLK), PLRAIN(:,:,JBLK), PRSUD(:,:,:,JBLK), PSTRCU(:,:,JBLK),     &
    & PSTRCV(:,:,JBLK), PFCQLF(:,:,JBLK),  PFCQIF(:,:,JBLK), PMFUDE_RATE(:,:,JBLK),                  &
    & PMFDDE_RATE(:,:,JBLK), PCAPE(:,JBLK), PWMEAN(:,JBLK), PDISS(:,:,JBLK), KTRAC, PCM1(:,:,:,JBLK),&
    & PTENC(:,:,:,JBLK), PSCAV, YLSTACK)  
  
  ENDDO

ENDDO
!$OMP END PARALLEL DO

!$acc end parallel

!$acc end data

IF (CLCASEOUT /='') THEN
  CALL SAVEALL
ENDIF

IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LHOOK) CALL DR_HOOK('MAIN_CUCALLN_MF',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE SAVEALL

REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENT_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENQ_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENU_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENV_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENC_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PARPRC_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTOPC_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBASEC_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTYPE_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCBOT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCTOP_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBOTSC_1(:,:) 
LOGICAL           , ALLOCATABLE   :: LDCUM_1(:,:) 
LOGICAL           , ALLOCATABLE   :: LDSC_1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLU_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDE_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDELI_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSNDE_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFU_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFD_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCQ_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCS_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCL_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCN_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCL_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCN_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLRAIN_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PRSUD_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCU_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCV_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQLF_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQIF_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFUDE_RATE_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFDDE_RATE_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCAPE_1(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PWMEAN_1(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDISS_1(:,:,:)

TYPE (DD12) :: YDD
CHARACTER*18 :: CLBLOCK
CHARACTER*256 :: CLFILE
INTEGER :: JBLK1

CALL YDD%INIT ([NPROMA, NGPBLKS], [NPROMA1, NGPBLKS1])

ALLOCATE (PTENT_1(NPROMA1,KLEV,NGPBLKS1))           ; CALL YDD%SHUFFLE (PTENT      , PTENT_1        )
ALLOCATE (PTENQ_1(NPROMA1,KLEV,NGPBLKS1))           ; CALL YDD%SHUFFLE (PTENQ      , PTENQ_1        )
ALLOCATE (PTENU_1(NPROMA1,KLEV,NGPBLKS1))           ; CALL YDD%SHUFFLE (PTENU      , PTENU_1        )
ALLOCATE (PTENV_1(NPROMA1,KLEV,NGPBLKS1))           ; CALL YDD%SHUFFLE (PTENV      , PTENV_1        )
ALLOCATE (PTENC_1(NPROMA1,KLEV,KTRAC,NGPBLKS1))     ; CALL YDD%SHUFFLE (PTENC      , PTENC_1        )
ALLOCATE (PARPRC_1(NPROMA1,NGPBLKS1))               ; CALL YDD%SHUFFLE (PARPRC     , PARPRC_1       )
ALLOCATE (KTOPC_1(NPROMA1,NGPBLKS1))                ; CALL YDD%SHUFFLE (KTOPC      , KTOPC_1        )
ALLOCATE (KBASEC_1(NPROMA1,NGPBLKS1))               ; CALL YDD%SHUFFLE (KBASEC     , KBASEC_1       )
ALLOCATE (KTYPE_1(NPROMA1,NGPBLKS1))                ; CALL YDD%SHUFFLE (KTYPE      , KTYPE_1        )
ALLOCATE (KCBOT_1(NPROMA1,NGPBLKS1))                ; CALL YDD%SHUFFLE (KCBOT      , KCBOT_1        )
ALLOCATE (KCTOP_1(NPROMA1,NGPBLKS1))                ; CALL YDD%SHUFFLE (KCTOP      , KCTOP_1        )
ALLOCATE (KBOTSC_1(NPROMA1,NGPBLKS1))               ; CALL YDD%SHUFFLE (KBOTSC     , KBOTSC_1       )
ALLOCATE (LDCUM_1(NPROMA1,NGPBLKS1))                ; CALL YDD%SHUFFLE (LDCUM      , LDCUM_1        )
ALLOCATE (LDSC_1(NPROMA1,NGPBLKS1))                 ; CALL YDD%SHUFFLE (LDSC       , LDSC_1         )
ALLOCATE (PLU_1(NPROMA1,KLEV,NGPBLKS1))             ; CALL YDD%SHUFFLE (PLU        , PLU_1          )
ALLOCATE (PLUDE_1(NPROMA1,KLEV,NGPBLKS1))           ; CALL YDD%SHUFFLE (PLUDE      , PLUDE_1        )
ALLOCATE (PLUDELI_1(NPROMA1,KLEV,4,NGPBLKS1))       ; CALL YDD%SHUFFLE (PLUDELI    , PLUDELI_1      )
ALLOCATE (PSNDE_1(NPROMA1,KLEV,2,NGPBLKS1))         ; CALL YDD%SHUFFLE (PSNDE      , PSNDE_1        )
ALLOCATE (PMFU_1(NPROMA1,KLEV,NGPBLKS1))            ; CALL YDD%SHUFFLE (PMFU       , PMFU_1         )
ALLOCATE (PMFD_1(NPROMA1,KLEV,NGPBLKS1))            ; CALL YDD%SHUFFLE (PMFD       , PMFD_1         )
ALLOCATE (PDIFCQ_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PDIFCQ     , PDIFCQ_1       )
ALLOCATE (PDIFCS_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PDIFCS     , PDIFCS_1       )
ALLOCATE (PFHPCL_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PFHPCL     , PFHPCL_1       )
ALLOCATE (PFHPCN_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PFHPCN     , PFHPCN_1       )
ALLOCATE (PFPLCL_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PFPLCL     , PFPLCL_1       )
ALLOCATE (PFPLCN_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PFPLCN     , PFPLCN_1       )
ALLOCATE (PLRAIN_1(NPROMA1,KLEV,NGPBLKS1))          ; CALL YDD%SHUFFLE (PLRAIN     , PLRAIN_1       )
ALLOCATE (PRSUD_1(NPROMA1,KLEV,2,NGPBLKS1))         ; CALL YDD%SHUFFLE (PRSUD      , PRSUD_1        )
ALLOCATE (PSTRCU_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PSTRCU     , PSTRCU_1       )
ALLOCATE (PSTRCV_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PSTRCV     , PSTRCV_1       )
ALLOCATE (PFCQLF_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PFCQLF     , PFCQLF_1       )
ALLOCATE (PFCQIF_1(NPROMA1,KLEV+1,NGPBLKS1))        ; CALL YDD%SHUFFLE (PFCQIF     , PFCQIF_1       )
ALLOCATE (PMFUDE_RATE_1(NPROMA1,KLEV,NGPBLKS1))     ; CALL YDD%SHUFFLE (PMFUDE_RATE, PMFUDE_RATE_1  )
ALLOCATE (PMFDDE_RATE_1(NPROMA1,KLEV,NGPBLKS1))     ; CALL YDD%SHUFFLE (PMFDDE_RATE, PMFDDE_RATE_1  )
ALLOCATE (PCAPE_1(NPROMA1,NGPBLKS1))                ; CALL YDD%SHUFFLE (PCAPE      , PCAPE_1        )
ALLOCATE (PWMEAN_1(NPROMA1,NGPBLKS1))               ; CALL YDD%SHUFFLE (PWMEAN     , PWMEAN_1       )
ALLOCATE (PDISS_1(NPROMA1,KLEV,NGPBLKS1))           ; CALL YDD%SHUFFLE (PDISS      , PDISS_1        )

CALL XRD_MKDIR (TRIM (CLCASEOUT))

DO JBLK1 = 1, NGPBLKS1

  WRITE (CLBLOCK, '(".",I8.8,".",I8.8)') JBLK1, 1

  CLFILE = TRIM (CLCASEOUT)//"/CUCALLN_MF.OUT"//TRIM(CLBLOCK)//".dat"

  IF (LLVERBOSE) WRITE (0, *) " WRITE "//TRIM (CLFILE)

  OPEN (ILUN, FILE=TRIM (CLFILE), FORM="UNFORMATTED", STATUS="NEW")
  WRITE (ILUN) PTENT_1(:,:,JBLK1)       
  WRITE (ILUN) PTENQ_1(:,:,JBLK1)       
  WRITE (ILUN) PTENU_1(:,:,JBLK1)       
  WRITE (ILUN) PTENV_1(:,:,JBLK1)       
  WRITE (ILUN) PTENC_1(:,:,:,JBLK1)     
  WRITE (ILUN) PARPRC_1(:,JBLK1)        
  WRITE (ILUN) KTOPC_1(:,JBLK1)         
  WRITE (ILUN) KBASEC_1(:,JBLK1)        
  WRITE (ILUN) KTYPE_1(:,JBLK1)         
  WRITE (ILUN) KCBOT_1(:,JBLK1)         
  WRITE (ILUN) KCTOP_1(:,JBLK1)         
  WRITE (ILUN) KBOTSC_1(:,JBLK1)        
  WRITE (ILUN) LDCUM_1(:,JBLK1)         
  WRITE (ILUN) LDSC_1(:,JBLK1)          
  WRITE (ILUN) PLU_1(:,:,JBLK1)         
  WRITE (ILUN) PLUDE_1(:,:,JBLK1)       
  WRITE (ILUN) PLUDELI_1(:,:,:,JBLK1)   
  WRITE (ILUN) PSNDE_1(:,:,:,JBLK1)     
  WRITE (ILUN) PMFU_1(:,:,JBLK1)        
  WRITE (ILUN) PMFD_1(:,:,JBLK1)        
  WRITE (ILUN) PDIFCQ_1(:,:,JBLK1)      
  WRITE (ILUN) PDIFCS_1(:,:,JBLK1)      
  WRITE (ILUN) PFHPCL_1(:,:,JBLK1)      
  WRITE (ILUN) PFHPCN_1(:,:,JBLK1)      
  WRITE (ILUN) PFPLCL_1(:,:,JBLK1)      
  WRITE (ILUN) PFPLCN_1(:,:,JBLK1)      
  WRITE (ILUN) PLRAIN_1(:,:,JBLK1)      
  WRITE (ILUN) PRSUD_1(:,:,:,JBLK1)     
  WRITE (ILUN) PSTRCU_1(:,:,JBLK1)      
  WRITE (ILUN) PSTRCV_1(:,:,JBLK1)      
  WRITE (ILUN) PFCQLF_1(:,:,JBLK1)      
  WRITE (ILUN) PFCQIF_1(:,:,JBLK1)      
  WRITE (ILUN) PMFUDE_RATE_1(:,:,JBLK1) 
  WRITE (ILUN) PMFDDE_RATE_1(:,:,JBLK1) 
  WRITE (ILUN) PCAPE_1(:,JBLK1)         
  WRITE (ILUN) PWMEAN_1(:,JBLK1)        
  WRITE (ILUN) PDISS_1(:,:,JBLK1)       
  CLOSE (ILUN)

ENDDO

END SUBROUTINE

SUBROUTINE DIFFALL

REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENT_OUT(:,:,:)      , PTENT_OUT_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENQ_OUT(:,:,:)      , PTENQ_OUT_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENU_OUT(:,:,:)      , PTENU_OUT_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENV_OUT(:,:,:)      , PTENV_OUT_1(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENC_OUT(:,:,:,:)    , PTENC_OUT_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PARPRC_OUT(:,:)       , PARPRC_OUT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTOPC_OUT(:,:)        , KTOPC_OUT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBASEC_OUT(:,:)       , KBASEC_OUT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTYPE_OUT(:,:)        , KTYPE_OUT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCBOT_OUT(:,:)        , KCBOT_OUT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCTOP_OUT(:,:)        , KCTOP_OUT_1(:,:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBOTSC_OUT(:,:)       , KBOTSC_OUT_1(:,:) 
LOGICAL           , ALLOCATABLE   :: LDCUM_OUT(:,:)        , LDCUM_OUT_1(:,:) 
LOGICAL           , ALLOCATABLE   :: LDSC_OUT(:,:)         , LDSC_OUT_1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLU_OUT(:,:,:)        , PLU_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDE_OUT(:,:,:)      , PLUDE_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDELI_OUT(:,:,:,:)  , PLUDELI_OUT_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSNDE_OUT(:,:,:,:)    , PSNDE_OUT_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFU_OUT(:,:,:)       , PMFU_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFD_OUT(:,:,:)       , PMFD_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCQ_OUT(:,:,:)     , PDIFCQ_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCS_OUT(:,:,:)     , PDIFCS_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCL_OUT(:,:,:)     , PFHPCL_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCN_OUT(:,:,:)     , PFHPCN_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCL_OUT(:,:,:)     , PFPLCL_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCN_OUT(:,:,:)     , PFPLCN_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLRAIN_OUT(:,:,:)     , PLRAIN_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PRSUD_OUT(:,:,:,:)    , PRSUD_OUT_1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCU_OUT(:,:,:)     , PSTRCU_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCV_OUT(:,:,:)     , PSTRCV_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQLF_OUT(:,:,:)     , PFCQLF_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQIF_OUT(:,:,:)     , PFCQIF_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFUDE_RATE_OUT(:,:,:), PMFUDE_RATE_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFDDE_RATE_OUT(:,:,:), PMFDDE_RATE_OUT_1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCAPE_OUT(:,:)        , PCAPE_OUT_1(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PWMEAN_OUT(:,:)       , PWMEAN_OUT_1(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDISS_OUT(:,:,:)      , PDISS_OUT_1(:,:,:)

TYPE (DD12) :: YDD
INTEGER :: JBLK1
CHARACTER*18 :: CLBLOCK
CHARACTER*256 :: CLFILE

ALLOCATE (PTENT_OUT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENT_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENQ_OUT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENQ_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENU_OUT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENU_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENV_OUT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENV_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENC_OUT(NPROMA,KLEV,KTRAC,NGPBLKS)) ; ALLOCATE (PTENC_OUT_1(NPROMA1,KLEV,KTRAC,NGPBLKS1))
ALLOCATE (PARPRC_OUT(NPROMA,NGPBLKS))           ; ALLOCATE (PARPRC_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (KTOPC_OUT(NPROMA,NGPBLKS))            ; ALLOCATE (KTOPC_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (KBASEC_OUT(NPROMA,NGPBLKS))           ; ALLOCATE (KBASEC_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (KTYPE_OUT(NPROMA,NGPBLKS))            ; ALLOCATE (KTYPE_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (KCBOT_OUT(NPROMA,NGPBLKS))            ; ALLOCATE (KCBOT_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (KCTOP_OUT(NPROMA,NGPBLKS))            ; ALLOCATE (KCTOP_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (KBOTSC_OUT(NPROMA,NGPBLKS))           ; ALLOCATE (KBOTSC_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (LDCUM_OUT(NPROMA,NGPBLKS))            ; ALLOCATE (LDCUM_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (LDSC_OUT(NPROMA,NGPBLKS))             ; ALLOCATE (LDSC_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (PLU_OUT(NPROMA,KLEV,NGPBLKS))         ; ALLOCATE (PLU_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PLUDE_OUT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PLUDE_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PLUDELI_OUT(NPROMA,KLEV,4,NGPBLKS))   ; ALLOCATE (PLUDELI_OUT_1(NPROMA1,KLEV,4,NGPBLKS1))
ALLOCATE (PSNDE_OUT(NPROMA,KLEV,2,NGPBLKS))     ; ALLOCATE (PSNDE_OUT_1(NPROMA1,KLEV,2,NGPBLKS1))
ALLOCATE (PMFU_OUT(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PMFU_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PMFD_OUT(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PMFD_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PDIFCQ_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PDIFCQ_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PDIFCS_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PDIFCS_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PFHPCL_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PFHPCL_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PFHPCN_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PFHPCN_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PFPLCL_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PFPLCL_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PFPLCN_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PFPLCN_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PLRAIN_OUT(NPROMA,KLEV,NGPBLKS))      ; ALLOCATE (PLRAIN_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PRSUD_OUT(NPROMA,KLEV,2,NGPBLKS))     ; ALLOCATE (PRSUD_OUT_1(NPROMA1,KLEV,2,NGPBLKS1))
ALLOCATE (PSTRCU_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PSTRCU_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PSTRCV_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PSTRCV_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PFCQLF_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PFCQLF_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PFCQIF_OUT(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PFCQIF_OUT_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PMFUDE_RATE_OUT(NPROMA,KLEV,NGPBLKS)) ; ALLOCATE (PMFUDE_RATE_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PMFDDE_RATE_OUT(NPROMA,KLEV,NGPBLKS)) ; ALLOCATE (PMFDDE_RATE_OUT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PCAPE_OUT(NPROMA,NGPBLKS))            ; ALLOCATE (PCAPE_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (PWMEAN_OUT(NPROMA,NGPBLKS))           ; ALLOCATE (PWMEAN_OUT_1(NPROMA1,NGPBLKS1))
ALLOCATE (PDISS_OUT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PDISS_OUT_1(NPROMA1,KLEV,NGPBLKS1))

CALL YDD%INIT ([NPROMA1, NGPBLKS1], [NPROMA, NGPBLKS])

DO JBLK1 = 1, NGPBLKS1

  WRITE (CLBLOCK, '(".",I8.8,".",I8.8)') JBLK1, 1
  CLFILE = TRIM (CLCASEREF)//"/CUCALLN_MF.OUT"//TRIM(CLBLOCK)//".dat"
  
  IF (LLVERBOSE) WRITE (0, *) " READ "//TRIM (CLFILE)

  OPEN (ILUN, FILE=TRIM (CLFILE), FORM="UNFORMATTED", STATUS="OLD")
  READ (ILUN) PTENT_OUT_1(:,:,JBLK1)       
  READ (ILUN) PTENQ_OUT_1(:,:,JBLK1)       
  READ (ILUN) PTENU_OUT_1(:,:,JBLK1)       
  READ (ILUN) PTENV_OUT_1(:,:,JBLK1)       
  READ (ILUN) PTENC_OUT_1(:,:,:,JBLK1)     
  READ (ILUN) PARPRC_OUT_1(:,JBLK1)        
  READ (ILUN) KTOPC_OUT_1(:,JBLK1)         
  READ (ILUN) KBASEC_OUT_1(:,JBLK1)        
  READ (ILUN) KTYPE_OUT_1(:,JBLK1)         
  READ (ILUN) KCBOT_OUT_1(:,JBLK1)         
  READ (ILUN) KCTOP_OUT_1(:,JBLK1)         
  READ (ILUN) KBOTSC_OUT_1(:,JBLK1)        
  READ (ILUN) LDCUM_OUT_1(:,JBLK1)         
  READ (ILUN) LDSC_OUT_1(:,JBLK1)          
  READ (ILUN) PLU_OUT_1(:,:,JBLK1)         
  READ (ILUN) PLUDE_OUT_1(:,:,JBLK1)       
  READ (ILUN) PLUDELI_OUT_1(:,:,:,JBLK1)   
  READ (ILUN) PSNDE_OUT_1(:,:,:,JBLK1)     
  READ (ILUN) PMFU_OUT_1(:,:,JBLK1)        
  READ (ILUN) PMFD_OUT_1(:,:,JBLK1)        
  READ (ILUN) PDIFCQ_OUT_1(:,:,JBLK1)      
  READ (ILUN) PDIFCS_OUT_1(:,:,JBLK1)      
  READ (ILUN) PFHPCL_OUT_1(:,:,JBLK1)      
  READ (ILUN) PFHPCN_OUT_1(:,:,JBLK1)      
  READ (ILUN) PFPLCL_OUT_1(:,:,JBLK1)      
  READ (ILUN) PFPLCN_OUT_1(:,:,JBLK1)      
  READ (ILUN) PLRAIN_OUT_1(:,:,JBLK1)      
  READ (ILUN) PRSUD_OUT_1(:,:,:,JBLK1)     
  READ (ILUN) PSTRCU_OUT_1(:,:,JBLK1)      
  READ (ILUN) PSTRCV_OUT_1(:,:,JBLK1)      
  READ (ILUN) PFCQLF_OUT_1(:,:,JBLK1)      
  READ (ILUN) PFCQIF_OUT_1(:,:,JBLK1)      
  READ (ILUN) PMFUDE_RATE_OUT_1(:,:,JBLK1) 
  READ (ILUN) PMFDDE_RATE_OUT_1(:,:,JBLK1) 
  READ (ILUN) PCAPE_OUT_1(:,JBLK1)         
  READ (ILUN) PWMEAN_OUT_1(:,JBLK1)        
  READ (ILUN) PDISS_OUT_1(:,:,JBLK1)       
  CLOSE (ILUN)

ENDDO

CALL YDD%SHUFFLE (PTENT_OUT_1          ,   PTENT_OUT         )
CALL YDD%SHUFFLE (PTENQ_OUT_1          ,   PTENQ_OUT         )
CALL YDD%SHUFFLE (PTENU_OUT_1          ,   PTENU_OUT         )
CALL YDD%SHUFFLE (PTENV_OUT_1          ,   PTENV_OUT         )
CALL YDD%SHUFFLE (PTENC_OUT_1          ,   PTENC_OUT         )
CALL YDD%SHUFFLE (PARPRC_OUT_1         ,   PARPRC_OUT        )
CALL YDD%SHUFFLE (KTOPC_OUT_1          ,   KTOPC_OUT         )
CALL YDD%SHUFFLE (KBASEC_OUT_1         ,   KBASEC_OUT        )
CALL YDD%SHUFFLE (KTYPE_OUT_1          ,   KTYPE_OUT         )
CALL YDD%SHUFFLE (KCBOT_OUT_1          ,   KCBOT_OUT         )
CALL YDD%SHUFFLE (KCTOP_OUT_1          ,   KCTOP_OUT         )
CALL YDD%SHUFFLE (KBOTSC_OUT_1         ,   KBOTSC_OUT        )
CALL YDD%SHUFFLE (LDCUM_OUT_1          ,   LDCUM_OUT         )
CALL YDD%SHUFFLE (LDSC_OUT_1           ,   LDSC_OUT          )
CALL YDD%SHUFFLE (PLU_OUT_1            ,   PLU_OUT           )
CALL YDD%SHUFFLE (PLUDE_OUT_1          ,   PLUDE_OUT         )
CALL YDD%SHUFFLE (PLUDELI_OUT_1        ,   PLUDELI_OUT       )
CALL YDD%SHUFFLE (PSNDE_OUT_1          ,   PSNDE_OUT         )
CALL YDD%SHUFFLE (PMFU_OUT_1           ,   PMFU_OUT          )
CALL YDD%SHUFFLE (PMFD_OUT_1           ,   PMFD_OUT          )
CALL YDD%SHUFFLE (PDIFCQ_OUT_1         ,   PDIFCQ_OUT        )
CALL YDD%SHUFFLE (PDIFCS_OUT_1         ,   PDIFCS_OUT        )
CALL YDD%SHUFFLE (PFHPCL_OUT_1         ,   PFHPCL_OUT        )
CALL YDD%SHUFFLE (PFHPCN_OUT_1         ,   PFHPCN_OUT        )
CALL YDD%SHUFFLE (PFPLCL_OUT_1         ,   PFPLCL_OUT        )
CALL YDD%SHUFFLE (PFPLCN_OUT_1         ,   PFPLCN_OUT        )
CALL YDD%SHUFFLE (PLRAIN_OUT_1         ,   PLRAIN_OUT        )
CALL YDD%SHUFFLE (PRSUD_OUT_1          ,   PRSUD_OUT         )
CALL YDD%SHUFFLE (PSTRCU_OUT_1         ,   PSTRCU_OUT        )
CALL YDD%SHUFFLE (PSTRCV_OUT_1         ,   PSTRCV_OUT        )
CALL YDD%SHUFFLE (PFCQLF_OUT_1         ,   PFCQLF_OUT        )
CALL YDD%SHUFFLE (PFCQIF_OUT_1         ,   PFCQIF_OUT        )
CALL YDD%SHUFFLE (PMFUDE_RATE_OUT_1    ,   PMFUDE_RATE_OUT   )
CALL YDD%SHUFFLE (PMFDDE_RATE_OUT_1    ,   PMFDDE_RATE_OUT   )
CALL YDD%SHUFFLE (PCAPE_OUT_1          ,   PCAPE_OUT         )
CALL YDD%SHUFFLE (PWMEAN_OUT_1         ,   PWMEAN_OUT        )
CALL YDD%SHUFFLE (PDISS_OUT_1          ,   PDISS_OUT         )


CALL DIFF ("PTENT",       PTENT,        PTENT_OUT)
CALL DIFF ("PTENQ",       PTENQ,        PTENQ_OUT)
CALL DIFF ("PTENU",       PTENU,        PTENU_OUT)
CALL DIFF ("PTENV",       PTENV,        PTENV_OUT)
CALL DIFF ("PTENC",       PTENC,        PTENC_OUT)
!CALL DIFF ("PARPRC",      PARPRC,       PARPRC_OUT)
!CALL DIFF ("KTOPC",       KTOPC,        KTOPC_OUT)
!CALL DIFF ("KBASEC",      KBASEC,       KBASEC_OUT)
CALL DIFF ("KTYPE",       KTYPE,        KTYPE_OUT)
CALL DIFF ("KCBOT",       KCBOT,        KCBOT_OUT)
CALL DIFF ("KCTOP",       KCTOP,        KCTOP_OUT)
CALL DIFF ("KBOTSC",      KBOTSC,       KBOTSC_OUT)
CALL DIFF ("LDCUM",       LDCUM,        LDCUM_OUT)
CALL DIFF ("LDSC",        LDSC,         LDSC_OUT)
CALL DIFF ("PLU",         PLU,          PLU_OUT)
CALL DIFF ("PLUDE",       PLUDE,        PLUDE_OUT)
CALL DIFF ("PLUDELI",     PLUDELI,      PLUDELI_OUT)
CALL DIFF ("PSNDE",       PSNDE,        PSNDE_OUT)
CALL DIFF ("PMFU",        PMFU,         PMFU_OUT)
CALL DIFF ("PMFD",        PMFD,         PMFD_OUT)
CALL DIFF ("PDIFCQ",      PDIFCQ,       PDIFCQ_OUT)
CALL DIFF ("PDIFCS",      PDIFCS,       PDIFCS_OUT)
CALL DIFF ("PFHPCL",      PFHPCL,       PFHPCL_OUT)
CALL DIFF ("PFHPCN",      PFHPCN,       PFHPCN_OUT)
CALL DIFF ("PFPLCL",      PFPLCL,       PFPLCL_OUT)
CALL DIFF ("PFPLCN",      PFPLCN,       PFPLCN_OUT)
CALL DIFF ("PLRAIN",      PLRAIN,       PLRAIN_OUT)
CALL DIFF ("PRSUD",       PRSUD,         PRSUD_OUT)
CALL DIFF ("PSTRCU",      PSTRCU,       PSTRCU_OUT)
CALL DIFF ("PSTRCV",      PSTRCV,       PSTRCV_OUT)
CALL DIFF ("PFCQLF",      PFCQLF,       PFCQLF_OUT)
CALL DIFF ("PFCQIF",      PFCQIF,       PFCQIF_OUT)
CALL DIFF ("PMFUDE_RATE", PMFUDE_RATE,  PMFUDE_RATE_OUT)
CALL DIFF ("PMFDDE_RATE", PMFDDE_RATE,  PMFDDE_RATE_OUT)
CALL DIFF ("PCAPE",       PCAPE,        PCAPE_OUT)
CALL DIFF ("PWMEAN",      PWMEAN,       PWMEAN_OUT)
CALL DIFF ("PDISS",       PDISS,        PDISS_OUT)

END SUBROUTINE

SUBROUTINE READALL

USE IEEE_ARITHMETIC, ONLY : IEEE_SIGNALING_NAN, IEEE_VALUE

LOGICAL,                  ALLOCATABLE :: LDLAND_1(:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PLCRIT_AER_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PTM1_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PQM1_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PUM1_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PVM1_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PCM1_1(:,:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PLITOT_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PVERVEL_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PQHFL_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PAHFS_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PAPHM1_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PAP_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PAPH_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PGEO_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PGEOH_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PTENT_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PTENQ_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PTENU_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PTENV_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PGAW_1(:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PCUCONVCA_1(:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PGP2DSPP_1(:,:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PDX_1(:,:)
REAL (KIND=JPRB),         ALLOCATABLE :: PTENC_1(:,:,:,:)
LOGICAL,                  ALLOCATABLE :: LDSHCV_1(:,:)

TYPE (DD12) :: YDD
INTEGER :: JBLK1
CHARACTER*18 :: CLBLOCK
CHARACTER*256 :: CLFILE
REAL (KIND=JPRB) :: ZNAN

ZNAN = IEEE_VALUE (ZNAN, IEEE_SIGNALING_NAN)

JBLK1 = 1

WRITE (CLBLOCK, '(".",I8.8,".",I8.8)') JBLK1, 1

OPEN (ILUN, FILE=TRIM(CLCASE)//"/CUCALLN_MF.CONST"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="OLD")
CALL LOAD (ILUN, YDTHF)
CALL LOAD (ILUN, YDCST)
CALL LOAD (ILUN, YDERAD)
CALL LOAD (ILUN, YDML_PHY_EC)
CALL LOAD (ILUN, YDML_PHY_SLIN)
CALL LOAD (ILUN, YGFL)
CLOSE (ILUN)

OPEN (ILUN, FILE=TRIM(CLCASE)//"/CUCALLN_MF.DIMS"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="OLD")
READ (ILUN) PPLDARE
READ (ILUN) PPLRG
READ (ILUN) KSTEP
READ (ILUN) NPROMA1 
READ (ILUN) KSMAX 
READ (ILUN) KLEV 
READ (ILUN) KSPPN2D
READ (ILUN) KTRAC 
READ (ILUN) KIDIA 
READ (ILUN) KFDIA 
READ (ILUN) LDSLPHY 
READ (ILUN) PTSPHY 
READ (ILUN) PVDIFTS
ALLOCATE (PSCAV(KTRAC))
READ (ILUN) PSCAV
CLOSE (ILUN)

! IN & INOUT

ALLOCATE (LDLAND(NPROMA,NGPBLKS))           ; ALLOCATE (LDLAND_1(NPROMA1,NGPBLKS1))
ALLOCATE (PLCRIT_AER(NPROMA,KLEV,NGPBLKS))  ; ALLOCATE (PLCRIT_AER_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTM1(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PTM1_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PQM1(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PQM1_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PUM1(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PUM1_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PVM1(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PVM1_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PCM1(NPROMA,KLEV,KTRAC,NGPBLKS))  ; ALLOCATE (PCM1_1(NPROMA1,KLEV,KTRAC,NGPBLKS1))
ALLOCATE (PLITOT(NPROMA,KLEV,NGPBLKS))      ; ALLOCATE (PLITOT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PVERVEL(NPROMA,KLEV,NGPBLKS))     ; ALLOCATE (PVERVEL_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PQHFL(NPROMA,KLEV+1,NGPBLKS))     ; ALLOCATE (PQHFL_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PAHFS(NPROMA,KLEV+1,NGPBLKS))     ; ALLOCATE (PAHFS_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PAPHM1(NPROMA,KLEV+1,NGPBLKS))    ; ALLOCATE (PAPHM1_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PAP(NPROMA,KLEV,NGPBLKS))         ; ALLOCATE (PAP_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PAPH(NPROMA,KLEV+1,NGPBLKS))      ; ALLOCATE (PAPH_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PGEO(NPROMA,KLEV,NGPBLKS))        ; ALLOCATE (PGEO_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PGEOH(NPROMA,KLEV+1,NGPBLKS))     ; ALLOCATE (PGEOH_1(NPROMA1,KLEV+1,NGPBLKS1))
ALLOCATE (PTENT(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENT_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENQ(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENQ_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENU(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENU_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PTENV(NPROMA,KLEV,NGPBLKS))       ; ALLOCATE (PTENV_1(NPROMA1,KLEV,NGPBLKS1))
ALLOCATE (PGAW(NPROMA,NGPBLKS))             ; ALLOCATE (PGAW_1(NPROMA1,NGPBLKS1))
ALLOCATE (PCUCONVCA(NPROMA,NGPBLKS))        ; ALLOCATE (PCUCONVCA_1(NPROMA1,NGPBLKS1))
ALLOCATE (PGP2DSPP(NPROMA,KSPPN2D,NGPBLKS)) ; ALLOCATE (PGP2DSPP_1(NPROMA1,KSPPN2D,NGPBLKS1))
ALLOCATE (PDX(NPROMA,NGPBLKS))              ; ALLOCATE (PDX_1(NPROMA1,NGPBLKS1))
ALLOCATE (PTENC(NPROMA,KLEV,KTRAC,NGPBLKS)) ; ALLOCATE (PTENC_1(NPROMA1,KLEV,KTRAC,NGPBLKS1))
ALLOCATE (LDSHCV(NPROMA,NGPBLKS))           ; ALLOCATE (LDSHCV_1(NPROMA1,NGPBLKS1))

! OUT

ALLOCATE (PARPRC(NPROMA,NGPBLKS))           ; PARPRC       = ZNAN
ALLOCATE (KTOPC(NPROMA,NGPBLKS))            ; KTOPC        = ZNAN
ALLOCATE (KBASEC(NPROMA,NGPBLKS))           ; KBASEC       = ZNAN
ALLOCATE (KTYPE(NPROMA,NGPBLKS))            ; KTYPE        = ZNAN
ALLOCATE (KCBOT(NPROMA,NGPBLKS))            ; KCBOT        = ZNAN
ALLOCATE (KCTOP(NPROMA,NGPBLKS))            ; KCTOP        = ZNAN
ALLOCATE (KBOTSC(NPROMA,NGPBLKS))           ; KBOTSC       = ZNAN
ALLOCATE (LDCUM(NPROMA,NGPBLKS))            ; LDCUM        = ZNAN
ALLOCATE (LDSC(NPROMA,NGPBLKS))             ; LDSC         = ZNAN
ALLOCATE (PLU(NPROMA,KLEV,NGPBLKS))         ; PLU          = ZNAN
ALLOCATE (PLUDE(NPROMA,KLEV,NGPBLKS))       ; PLUDE        = ZNAN
ALLOCATE (PLUDELI(NPROMA,KLEV,4,NGPBLKS))   ; PLUDELI      = ZNAN
ALLOCATE (PSNDE(NPROMA,KLEV,2,NGPBLKS))     ; PSNDE        = ZNAN
ALLOCATE (PMFU(NPROMA,KLEV,NGPBLKS))        ; PMFU         = ZNAN
ALLOCATE (PMFD(NPROMA,KLEV,NGPBLKS))        ; PMFD         = ZNAN
ALLOCATE (PDIFCQ(NPROMA,KLEV+1,NGPBLKS))    ; PDIFCQ       = ZNAN
ALLOCATE (PDIFCS(NPROMA,KLEV+1,NGPBLKS))    ; PDIFCS       = ZNAN
ALLOCATE (PFHPCL(NPROMA,KLEV+1,NGPBLKS))    ; PFHPCL       = ZNAN
ALLOCATE (PFHPCN(NPROMA,KLEV+1,NGPBLKS))    ; PFHPCN       = ZNAN
ALLOCATE (PFPLCL(NPROMA,KLEV+1,NGPBLKS))    ; PFPLCL       = ZNAN
ALLOCATE (PFPLCN(NPROMA,KLEV+1,NGPBLKS))    ; PFPLCN       = ZNAN
ALLOCATE (PLRAIN(NPROMA,KLEV,NGPBLKS))      ; PLRAIN       = ZNAN
ALLOCATE (PRSUD(NPROMA,KLEV,2,NGPBLKS))     ; PRSUD        = ZNAN
ALLOCATE (PSTRCU(NPROMA,KLEV+1,NGPBLKS))    ; PSTRCU       = ZNAN
ALLOCATE (PSTRCV(NPROMA,KLEV+1,NGPBLKS))    ; PSTRCV       = ZNAN
ALLOCATE (PFCQLF(NPROMA,KLEV+1,NGPBLKS))    ; PFCQLF       = ZNAN
ALLOCATE (PFCQIF(NPROMA,KLEV+1,NGPBLKS))    ; PFCQIF       = ZNAN
ALLOCATE (PMFUDE_RATE(NPROMA,KLEV,NGPBLKS)) ; PMFUDE_RATE  = ZNAN
ALLOCATE (PMFDDE_RATE(NPROMA,KLEV,NGPBLKS)) ; PMFDDE_RATE  = ZNAN
ALLOCATE (PCAPE(NPROMA,NGPBLKS))            ; PCAPE        = ZNAN
ALLOCATE (PWMEAN(NPROMA,NGPBLKS))           ; PWMEAN       = ZNAN
ALLOCATE (PDISS(NPROMA,KLEV,NGPBLKS))       ; PDISS        = ZNAN

CALL YDD%INIT ([NPROMA1, NGPBLKS1], [NPROMA, NGPBLKS])

DO JBLK1 = 1, NGPBLKS1

  WRITE (CLBLOCK, '(".",I8.8,".",I8.8)') JBLK1, 1

  CLFILE = TRIM(CLCASE)//"/CUCALLN_MF.IN"//TRIM(CLBLOCK)//".dat"

  IF (LLVERBOSE) WRITE (0, *) " READ "//TRIM (CLFILE)

  OPEN (ILUN, FILE=TRIM(CLFILE), FORM="UNFORMATTED", STATUS="OLD")
  READ (ILUN) LDLAND_1(:,JBLK1)        
  READ (ILUN) PLCRIT_AER_1(:,:,JBLK1)  
  READ (ILUN) PTM1_1(:,:,JBLK1)        
  READ (ILUN) PQM1_1(:,:,JBLK1)        
  READ (ILUN) PUM1_1(:,:,JBLK1)        
  READ (ILUN) PVM1_1(:,:,JBLK1)        
  READ (ILUN) PCM1_1(:,:,:,JBLK1)      
  READ (ILUN) PLITOT_1(:,:,JBLK1)      
  READ (ILUN) PVERVEL_1(:,:,JBLK1)     
  READ (ILUN) PQHFL_1(:,:,JBLK1)       
  READ (ILUN) PAHFS_1(:,:,JBLK1)       
  READ (ILUN) PAPHM1_1(:,:,JBLK1)      
  READ (ILUN) PAP_1(:,:,JBLK1)         
  READ (ILUN) PAPH_1(:,:,JBLK1)        
  READ (ILUN) PGEO_1(:,:,JBLK1)        
  READ (ILUN) PGEOH_1(:,:,JBLK1)       
  READ (ILUN) PTENT_1(:,:,JBLK1)       
  READ (ILUN) PTENQ_1(:,:,JBLK1)       
  READ (ILUN) PTENU_1(:,:,JBLK1)       
  READ (ILUN) PTENV_1(:,:,JBLK1)       
  READ (ILUN) PGAW_1(:,JBLK1)          
  READ (ILUN) PCUCONVCA_1(:,JBLK1)     
  READ (ILUN) PGP2DSPP_1(:,:,JBLK1)    
  READ (ILUN) PDX_1(:,JBLK1)           
  READ (ILUN) PTENC_1(:,:,:,JBLK1)     
  READ (ILUN) LDSHCV_1(:,JBLK1)        
  CLOSE (ILUN)

ENDDO

CALL YDD%SHUFFLE (LDLAND_1          , LDLAND      )
CALL YDD%SHUFFLE (PLCRIT_AER_1      , PLCRIT_AER  )
CALL YDD%SHUFFLE (PTM1_1            , PTM1        )
CALL YDD%SHUFFLE (PQM1_1            , PQM1        )
CALL YDD%SHUFFLE (PUM1_1            , PUM1        )
CALL YDD%SHUFFLE (PVM1_1            , PVM1        )
CALL YDD%SHUFFLE (PCM1_1            , PCM1        )
CALL YDD%SHUFFLE (PLITOT_1          , PLITOT      )
CALL YDD%SHUFFLE (PVERVEL_1         , PVERVEL     )
CALL YDD%SHUFFLE (PQHFL_1           , PQHFL       )
CALL YDD%SHUFFLE (PAHFS_1           , PAHFS       )
CALL YDD%SHUFFLE (PAPHM1_1          , PAPHM1      )
CALL YDD%SHUFFLE (PAP_1             , PAP         )
CALL YDD%SHUFFLE (PAPH_1            , PAPH        )
CALL YDD%SHUFFLE (PGEO_1            , PGEO        )
CALL YDD%SHUFFLE (PGEOH_1           , PGEOH       )
CALL YDD%SHUFFLE (PTENT_1           , PTENT       )
CALL YDD%SHUFFLE (PTENQ_1           , PTENQ       )
CALL YDD%SHUFFLE (PTENU_1           , PTENU       )
CALL YDD%SHUFFLE (PTENV_1           , PTENV       )
CALL YDD%SHUFFLE (PGAW_1            , PGAW        )
CALL YDD%SHUFFLE (PCUCONVCA_1       , PCUCONVCA   )
CALL YDD%SHUFFLE (PGP2DSPP_1        , PGP2DSPP    )
CALL YDD%SHUFFLE (PDX_1             , PDX         )
CALL YDD%SHUFFLE (PTENC_1           , PTENC       )
CALL YDD%SHUFFLE (LDSHCV_1          , LDSHCV      )

END SUBROUTINE

END 

