PROGRAM MAIN

USE MODEL_PHYSICS_ECMWF_MOD      , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD                       , ONLY : TERAD
USE YOM_YGFL                     , ONLY : TYPE_GFLD
USE PARKIND1                     , ONLY : JPIM     ,JPRB
USE YOMHOOK                      , ONLY : LHOOK,   DR_HOOK

USE YOMCST                       , ONLY : TCST  
USE YOETHF                       , ONLY : TTHF 

USE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD
USE UTIL_TERAD_MOD
USE UTIL_TYPE_GFLD_MOD
USE UTIL_TCST_MOD
USE UTIL_TTHF_MOD

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV
USE STACK_MOD

IMPLICIT NONE


REAL(KIND=JPRB)       :: PPLDARE
REAL(KIND=JPRB)       :: PPLRG
INTEGER(KIND=JPIM)    :: KSTEP

TYPE(TTHF)                          :: YDTHF
TYPE(TCST)                          :: YDCST
TYPE(TERAD)                         :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE)      :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE) :: YDML_PHY_SLIN
TYPE(TYPE_GFLD)                     :: YGFL

INTEGER(KIND=JPIM)    :: NGPTOT 
INTEGER(KIND=JPIM)    :: KSMAX 
INTEGER(KIND=JPIM)    :: KLEV 
INTEGER(KIND=JPIM)    :: KSPPN2D
INTEGER(KIND=JPIM)    :: KTRAC 
INTEGER(KIND=JPIM)    :: KIDIA 
INTEGER(KIND=JPIM)    :: KFDIA 
LOGICAL               :: LDSLPHY 
REAL(KIND=JPRB)       :: PTSPHY 
REAL(KIND=JPRB)       :: PVDIFTS
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSCAV(:) 

LOGICAL           , ALLOCATABLE   :: LDLAND(:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLCRIT_AER(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTM1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PQM1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PUM1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PVM1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLITOT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PVERVEL(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PQHFL(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAHFS(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAPHM1(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAP(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAPH(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGEO(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGEOH(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENT(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENQ(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENU(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENV(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGAW(:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCUCONVCA(:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGP2DSPP(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDX(:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENC(:,:,:) 
LOGICAL           , ALLOCATABLE   :: LDSHCV(:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PARPRC(:)        
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTOPC(:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBASEC(:)        
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTYPE(:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCBOT(:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCTOP(:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBOTSC(:)        
LOGICAL           , ALLOCATABLE   :: LDCUM(:)         
LOGICAL           , ALLOCATABLE   :: LDSC(:)          
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLU(:,:)         
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDE(:,:)       
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDELI(:,:,:)   
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSNDE(:,:,:)     
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFU(:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFD(:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCQ(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCS(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCL(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCN(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCL(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCN(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLRAIN(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PRSUD(:,:,:)     
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCU(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCV(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQLF(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQIF(:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFUDE_RATE(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFDDE_RATE(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCAPE(:)         
REAL(KIND=JPRB)   , ALLOCATABLE   :: PWMEAN(:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDISS(:,:)       

TYPE (STACK) :: YLSTACK
REAL (KIND=JPRB), ALLOCATABLE :: ZSTACK (:,:)

#include "cucalln_mf.intfb.h"

INTERFACE DIFF
  PROCEDURE :: DIFFR1, DIFFR2, DIFFR3, DIFFL1, DIFFI1
END INTERFACE

INTEGER (KIND=JPIM), PARAMETER :: ILUN = 77
INTEGER (KIND=JPIM) :: JLON

INTEGER (KIND=JPIM) :: ISTACK
CHARACTER*18 :: CLBLOCK
LOGICAL :: LLDIFF
CHARACTER(LEN=256) :: CLCASE, CLCASEREF, CLCASEOUT

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MAIN_CUCALLN_MF',0,ZHOOK_HANDLE)


CALL INITOPTIONS 
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CLCASEREF=CLCASE
CALL GETOPTION ("--case-ref", CLCASEREF)
CLCASEOUT = ''
CALL GETOPTION ("--case-out", CLCASEOUT)
ISTACK = 100
CALL GETOPTION ("--stack", ISTACK)
CALL CHECKOPTIONS

WRITE (CLBLOCK, '(".",I8.8,".",I8.8)') 1, 1

CALL READALL

CALL COPY (YDTHF)
CALL COPY (YDCST)
CALL COPY (YDERAD)
CALL COPY (YDML_PHY_EC)
CALL COPY (YDML_PHY_SLIN)
CALL COPY (YGFL)

WRITE (0, *) " NGPTOT = ", NGPTOT, " KLEV = ", KLEV

ALLOCATE (ZSTACK (NGPTOT*KLEV*ISTACK, 1))

!$acc data present (YDTHF, YDCST, YDERAD, YDML_PHY_SLIN,  YDML_PHY_EC, YGFL) &
!$acc   & copy (LDLAND, PLCRIT_AER, PTM1, PQM1, PUM1, PVM1, PCM1, PLITOT, PVERVEL, &
!$acc   &       PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO, PGEOH, PTENT, PTENQ, PTENU, PTENV, PGAW, &
!$acc   &       PCUCONVCA, PGP2DSPP, PSCAV, PDX, PTENC, PARPRC, KTOPC, KBASEC, KTYPE, KCBOT, &
!$acc   &       KCTOP, KBOTSC, LDCUM, LDSC, LDSHCV, PLU, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, &
!$acc   &       PDIFCQ, PDIFCS, PFHPCL, PFHPCN, PFPLCL, PFPLCN, PLRAIN, PRSUD, PSTRCU, PSTRCV, &
!$acc   &       PFCQLF, PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWMEAN, PDISS) &
!$acc   & create (ZSTACK)

!$acc serial

YLSTACK%L = LOC (ZSTACK (1, 1))
YLSTACK%U = YLSTACK%L + SIZE (ZSTACK, 1) * KIND (ZSTACK)

DO JLON = 1, NGPTOT

KIDIA = JLON
KFDIA = JLON

CALL CUCALLN_MF    (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN,  YDML_PHY_EC, YGFL,     &
& KIDIA, KFDIA, NGPTOT, KSMAX, KLEV, PDX, KSPPN2D, LDLAND, LDSLPHY, PTSPHY,  PVDIFTS, PTM1, PQM1, PUM1, &
& PVM1, PLITOT, PVERVEL, PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO,  PGEOH, PGAW, PCUCONVCA, PGP2DSPP,      &
& PTENT, PTENQ, PTENU, PTENV, PARPRC, KTOPC, KBASEC, KTYPE,    KCBOT, KCTOP, KBOTSC, LDCUM, LDSC,       &
& LDSHCV, PLCRIT_AER, PLU, PLUDE, PLUDELI, PSNDE, PMFU,  PMFD, PDIFCQ, PDIFCS, PFHPCL, PFHPCN,          &
& PFPLCL, PFPLCN, PLRAIN, PRSUD, PSTRCU, PSTRCV, PFCQLF,  PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE,      &
& PWMEAN, PDISS, KTRAC, PCM1, PTENC, PSCAV, YLSTACK )  

ENDDO

!$acc end serial

!$acc end data

IF (CLCASEOUT /='') THEN
  CALL SAVEALL
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF



IF (LHOOK) CALL DR_HOOK('MAIN_CUCALLN_MF',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE SAVEALL

CALL XRD_MKDIR (TRIM (CLCASEOUT))

OPEN (ILUN, FILE=TRIM (CLCASEOUT)//"/CUCALLN_MF.OUT"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="NEW")
WRITE (ILUN) PTENT
WRITE (ILUN) PTENQ
WRITE (ILUN) PTENU
WRITE (ILUN) PTENV
WRITE (ILUN) PTENC
WRITE (ILUN) PARPRC
WRITE (ILUN) KTOPC
WRITE (ILUN) KBASEC
WRITE (ILUN) KTYPE
WRITE (ILUN) KCBOT
WRITE (ILUN) KCTOP
WRITE (ILUN) KBOTSC
WRITE (ILUN) LDCUM
WRITE (ILUN) LDSC
WRITE (ILUN) PLU
WRITE (ILUN) PLUDE
WRITE (ILUN) PLUDELI
WRITE (ILUN) PSNDE
WRITE (ILUN) PMFU
WRITE (ILUN) PMFD
WRITE (ILUN) PDIFCQ
WRITE (ILUN) PDIFCS
WRITE (ILUN) PFHPCL
WRITE (ILUN) PFHPCN
WRITE (ILUN) PFPLCL
WRITE (ILUN) PFPLCN
WRITE (ILUN) PLRAIN
WRITE (ILUN) PRSUD
WRITE (ILUN) PSTRCU
WRITE (ILUN) PSTRCV
WRITE (ILUN) PFCQLF
WRITE (ILUN) PFCQIF
WRITE (ILUN) PMFUDE_RATE
WRITE (ILUN) PMFDDE_RATE
WRITE (ILUN) PCAPE
WRITE (ILUN) PWMEAN
WRITE (ILUN) PDISS
CLOSE (ILUN)

END SUBROUTINE

SUBROUTINE DIFFALL

REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENT_OUT(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENQ_OUT(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENU_OUT(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENV_OUT(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENC_OUT(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PARPRC_OUT(:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTOPC_OUT(:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBASEC_OUT(:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTYPE_OUT(:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCBOT_OUT(:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCTOP_OUT(:) 
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBOTSC_OUT(:) 
LOGICAL           , ALLOCATABLE   :: LDCUM_OUT(:) 
LOGICAL           , ALLOCATABLE   :: LDSC_OUT(:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLU_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDE_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDELI_OUT(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSNDE_OUT(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFU_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFD_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCQ_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCS_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCL_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCN_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCL_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCN_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLRAIN_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PRSUD_OUT(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCU_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCV_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQLF_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQIF_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFUDE_RATE_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFDDE_RATE_OUT(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCAPE_OUT(:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PWMEAN_OUT(:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDISS_OUT(:,:)

ALLOCATE (PTENT_OUT(NGPTOT,KLEV))
ALLOCATE (PTENQ_OUT(NGPTOT,KLEV))
ALLOCATE (PTENU_OUT(NGPTOT,KLEV))
ALLOCATE (PTENV_OUT(NGPTOT,KLEV))
ALLOCATE (PTENC_OUT(NGPTOT,KLEV,KTRAC))
ALLOCATE (PARPRC_OUT(NGPTOT))
ALLOCATE (KTOPC_OUT(NGPTOT))
ALLOCATE (KBASEC_OUT(NGPTOT))
ALLOCATE (KTYPE_OUT(NGPTOT))
ALLOCATE (KCBOT_OUT(NGPTOT))
ALLOCATE (KCTOP_OUT(NGPTOT))
ALLOCATE (KBOTSC_OUT(NGPTOT))
ALLOCATE (LDCUM_OUT(NGPTOT))
ALLOCATE (LDSC_OUT(NGPTOT))
ALLOCATE (PLU_OUT(NGPTOT,KLEV))
ALLOCATE (PLUDE_OUT(NGPTOT,KLEV))
ALLOCATE (PLUDELI_OUT(NGPTOT,KLEV,4))
ALLOCATE (PSNDE_OUT(NGPTOT,KLEV,2))
ALLOCATE (PMFU_OUT(NGPTOT,KLEV))
ALLOCATE (PMFD_OUT(NGPTOT,KLEV))
ALLOCATE (PDIFCQ_OUT(NGPTOT,KLEV+1))
ALLOCATE (PDIFCS_OUT(NGPTOT,KLEV+1))
ALLOCATE (PFHPCL_OUT(NGPTOT,KLEV+1))
ALLOCATE (PFHPCN_OUT(NGPTOT,KLEV+1))
ALLOCATE (PFPLCL_OUT(NGPTOT,KLEV+1))
ALLOCATE (PFPLCN_OUT(NGPTOT,KLEV+1))
ALLOCATE (PLRAIN_OUT(NGPTOT,KLEV))
ALLOCATE (PRSUD_OUT(NGPTOT,KLEV,2))
ALLOCATE (PSTRCU_OUT(NGPTOT,KLEV+1))
ALLOCATE (PSTRCV_OUT(NGPTOT,KLEV+1))
ALLOCATE (PFCQLF_OUT(NGPTOT,KLEV+1))
ALLOCATE (PFCQIF_OUT(NGPTOT,KLEV+1))
ALLOCATE (PMFUDE_RATE_OUT(NGPTOT,KLEV))
ALLOCATE (PMFDDE_RATE_OUT(NGPTOT,KLEV))
ALLOCATE (PCAPE_OUT(NGPTOT))
ALLOCATE (PWMEAN_OUT(NGPTOT))
ALLOCATE (PDISS_OUT(NGPTOT,KLEV))

OPEN (ILUN, FILE=TRIM (CLCASEREF)//"/CUCALLN_MF.OUT"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="OLD")
READ (ILUN) PTENT_OUT
READ (ILUN) PTENQ_OUT
READ (ILUN) PTENU_OUT
READ (ILUN) PTENV_OUT
READ (ILUN) PTENC_OUT
READ (ILUN) PARPRC_OUT
READ (ILUN) KTOPC_OUT
READ (ILUN) KBASEC_OUT
READ (ILUN) KTYPE_OUT
READ (ILUN) KCBOT_OUT
READ (ILUN) KCTOP_OUT
READ (ILUN) KBOTSC_OUT
READ (ILUN) LDCUM_OUT
READ (ILUN) LDSC_OUT
READ (ILUN) PLU_OUT
READ (ILUN) PLUDE_OUT
READ (ILUN) PLUDELI_OUT
READ (ILUN) PSNDE_OUT
READ (ILUN) PMFU_OUT
READ (ILUN) PMFD_OUT
READ (ILUN) PDIFCQ_OUT
READ (ILUN) PDIFCS_OUT
READ (ILUN) PFHPCL_OUT
READ (ILUN) PFHPCN_OUT
READ (ILUN) PFPLCL_OUT
READ (ILUN) PFPLCN_OUT
READ (ILUN) PLRAIN_OUT
READ (ILUN) PRSUD_OUT
READ (ILUN) PSTRCU_OUT
READ (ILUN) PSTRCV_OUT
READ (ILUN) PFCQLF_OUT
READ (ILUN) PFCQIF_OUT
READ (ILUN) PMFUDE_RATE_OUT
READ (ILUN) PMFDDE_RATE_OUT
READ (ILUN) PCAPE_OUT
READ (ILUN) PWMEAN_OUT
READ (ILUN) PDISS_OUT
CLOSE (ILUN)

CALL DIFF ("PTENT",       PTENT,        PTENT_OUT)
CALL DIFF ("PTENQ",       PTENQ,        PTENQ_OUT)
CALL DIFF ("PTENU",       PTENU,        PTENU_OUT)
CALL DIFF ("PTENV",       PTENV,        PTENV_OUT)
CALL DIFF ("PTENC",       PTENC,        PTENC_OUT)
CALL DIFF ("PARPRC",      PARPRC,       PARPRC_OUT)
!CALL DIFF ("KTOPC",       KTOPC,        KTOPC_OUT)
!CALL DIFF ("KBASEC",      KBASEC,       KBASEC_OUT)
CALL DIFF ("KTYPE",       KTYPE,        KTYPE_OUT)
CALL DIFF ("KCBOT",       KCBOT,        KCBOT_OUT)
CALL DIFF ("KCTOP",       KCTOP,        KCTOP_OUT)
CALL DIFF ("KBOTSC",      KBOTSC,       KBOTSC_OUT)
CALL DIFF ("LDCUM",       LDCUM,        LDCUM_OUT)
CALL DIFF ("LDSC",        LDSC,         LDSC_OUT)
CALL DIFF ("PLU",         PLU,          PLU_OUT)
CALL DIFF ("PLUDE",       PLUDE,        PLUDE_OUT)
CALL DIFF ("PLUDELI",     PLUDELI,      PLUDELI_OUT)
CALL DIFF ("PSNDE",       PSNDE,        PSNDE_OUT)
CALL DIFF ("PMFU",        PMFU,         PMFU_OUT)
CALL DIFF ("PMFD",        PMFD,         PMFD_OUT)
CALL DIFF ("PDIFCQ",      PDIFCQ,       PDIFCQ_OUT)
CALL DIFF ("PDIFCS",      PDIFCS,       PDIFCS_OUT)
CALL DIFF ("PFHPCL",      PFHPCL,       PFHPCL_OUT)
CALL DIFF ("PFHPCN",      PFHPCN,       PFHPCN_OUT)
CALL DIFF ("PFPLCL",      PFPLCL,       PFPLCL_OUT)
CALL DIFF ("PFPLCN",      PFPLCN,       PFPLCN_OUT)
CALL DIFF ("PLRAIN",      PLRAIN,       PLRAIN_OUT)
CALL DIFF ("PRSUD",       PRSUD,        PRSUD_OUT)
CALL DIFF ("PSTRCU",      PSTRCU,       PSTRCU_OUT)
CALL DIFF ("PSTRCV",      PSTRCV,       PSTRCV_OUT)
CALL DIFF ("PFCQLF",      PFCQLF,       PFCQLF_OUT)
CALL DIFF ("PFCQIF",      PFCQIF,       PFCQIF_OUT)
CALL DIFF ("PMFUDE_RATE", PMFUDE_RATE,  PMFUDE_RATE_OUT)
CALL DIFF ("PMFDDE_RATE", PMFDDE_RATE,  PMFDDE_RATE_OUT)
CALL DIFF ("PCAPE",       PCAPE,        PCAPE_OUT)
CALL DIFF ("PWMEAN",      PWMEAN,       PWMEAN_OUT)
CALL DIFF ("PDISS",       PDISS,        PDISS_OUT)

END SUBROUTINE

SUBROUTINE READALL

OPEN (ILUN, FILE=TRIM(CLCASE)//"/CUCALLN_MF.CONST"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="OLD")
CALL LOAD (ILUN, YDTHF)
CALL LOAD (ILUN, YDCST)
CALL LOAD (ILUN, YDERAD)
CALL LOAD (ILUN, YDML_PHY_EC)
CALL LOAD (ILUN, YDML_PHY_SLIN)
CALL LOAD (ILUN, YGFL)
CLOSE (ILUN)

OPEN (ILUN, FILE=TRIM(CLCASE)//"/CUCALLN_MF.DIMS"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="OLD")
READ (ILUN) PPLDARE
READ (ILUN) PPLRG
READ (ILUN) KSTEP
READ (ILUN) NGPTOT 
READ (ILUN) KSMAX 
READ (ILUN) KLEV 
READ (ILUN) KSPPN2D
READ (ILUN) KTRAC 
READ (ILUN) KIDIA 
READ (ILUN) KFDIA 
READ (ILUN) LDSLPHY 
READ (ILUN) PTSPHY 
READ (ILUN) PVDIFTS
ALLOCATE (PSCAV(KTRAC))
READ (ILUN) PSCAV
CLOSE (ILUN)

ALLOCATE (LDLAND(NGPTOT))
ALLOCATE (PLCRIT_AER(NGPTOT,KLEV))
ALLOCATE (PTM1(NGPTOT,KLEV))
ALLOCATE (PQM1(NGPTOT,KLEV))
ALLOCATE (PUM1(NGPTOT,KLEV))
ALLOCATE (PVM1(NGPTOT,KLEV))
ALLOCATE (PCM1(NGPTOT,KLEV,KTRAC))
ALLOCATE (PLITOT(NGPTOT,KLEV))
ALLOCATE (PVERVEL(NGPTOT,KLEV))
ALLOCATE (PQHFL(NGPTOT,KLEV+1))
ALLOCATE (PAHFS(NGPTOT,KLEV+1))
ALLOCATE (PAPHM1(NGPTOT,KLEV+1))
ALLOCATE (PAP(NGPTOT,KLEV))
ALLOCATE (PAPH(NGPTOT,KLEV+1))
ALLOCATE (PGEO(NGPTOT,KLEV))
ALLOCATE (PGEOH(NGPTOT,KLEV+1))
ALLOCATE (PTENT(NGPTOT,KLEV))
ALLOCATE (PTENQ(NGPTOT,KLEV))
ALLOCATE (PTENU(NGPTOT,KLEV))
ALLOCATE (PTENV(NGPTOT,KLEV))
ALLOCATE (PGAW(NGPTOT))
ALLOCATE (PCUCONVCA(NGPTOT))
ALLOCATE (PGP2DSPP(NGPTOT,KSPPN2D))
ALLOCATE (PDX(NGPTOT))
ALLOCATE (PTENC(NGPTOT,KLEV,KTRAC))
ALLOCATE (LDSHCV(NGPTOT))
ALLOCATE (PARPRC(NGPTOT))
ALLOCATE (KTOPC(NGPTOT))
ALLOCATE (KBASEC(NGPTOT))
ALLOCATE (KTYPE(NGPTOT))
ALLOCATE (KCBOT(NGPTOT))
ALLOCATE (KCTOP(NGPTOT))
ALLOCATE (KBOTSC(NGPTOT))
ALLOCATE (LDCUM(NGPTOT))
ALLOCATE (LDSC(NGPTOT))
ALLOCATE (PLU(NGPTOT,KLEV))
ALLOCATE (PLUDE(NGPTOT,KLEV))
ALLOCATE (PLUDELI(NGPTOT,KLEV,4))
ALLOCATE (PSNDE(NGPTOT,KLEV,2))
ALLOCATE (PMFU(NGPTOT,KLEV))
ALLOCATE (PMFD(NGPTOT,KLEV))
ALLOCATE (PDIFCQ(NGPTOT,KLEV+1))
ALLOCATE (PDIFCS(NGPTOT,KLEV+1))
ALLOCATE (PFHPCL(NGPTOT,KLEV+1))
ALLOCATE (PFHPCN(NGPTOT,KLEV+1))
ALLOCATE (PFPLCL(NGPTOT,KLEV+1))
ALLOCATE (PFPLCN(NGPTOT,KLEV+1))
ALLOCATE (PLRAIN(NGPTOT,KLEV))
ALLOCATE (PRSUD(NGPTOT,KLEV,2))
ALLOCATE (PSTRCU(NGPTOT,KLEV+1))
ALLOCATE (PSTRCV(NGPTOT,KLEV+1))
ALLOCATE (PFCQLF(NGPTOT,KLEV+1))
ALLOCATE (PFCQIF(NGPTOT,KLEV+1))
ALLOCATE (PMFUDE_RATE(NGPTOT,KLEV))
ALLOCATE (PMFDDE_RATE(NGPTOT,KLEV))
ALLOCATE (PCAPE(NGPTOT))
ALLOCATE (PWMEAN(NGPTOT))
ALLOCATE (PDISS(NGPTOT,KLEV))

OPEN (ILUN, FILE=TRIM(CLCASE)//"/CUCALLN_MF.IN"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="OLD")
READ (ILUN) LDLAND
READ (ILUN) PLCRIT_AER
READ (ILUN) PTM1
READ (ILUN) PQM1
READ (ILUN) PUM1
READ (ILUN) PVM1
READ (ILUN) PCM1
READ (ILUN) PLITOT
READ (ILUN) PVERVEL
READ (ILUN) PQHFL
READ (ILUN) PAHFS
READ (ILUN) PAPHM1
READ (ILUN) PAP
READ (ILUN) PAPH
READ (ILUN) PGEO
READ (ILUN) PGEOH
READ (ILUN) PTENT
READ (ILUN) PTENQ
READ (ILUN) PTENU
READ (ILUN) PTENV
READ (ILUN) PGAW
READ (ILUN) PCUCONVCA
READ (ILUN) PGP2DSPP
READ (ILUN) PDX
READ (ILUN) PTENC
READ (ILUN) LDSHCV
CLOSE (ILUN)

END SUBROUTINE

SUBROUTINE DIFFR1 (CDN, PA, PB)

CHARACTER (LEN=*) :: CDN
REAL (KIND=JPRB) :: PA (:), PB (:)

INTEGER :: I1

PRINT *, CDN

DO I1 = 1, SIZE (PA)
  IF (PA (I1) /= PB (I1)) THEN
    WRITE (*, '(I6," ",3E30.20)') I1, PA (I1), PB (I1), PA (I1) - PB (I1)
  ENDIF
ENDDO

END SUBROUTINE

SUBROUTINE DIFFR2 (CDN, PA, PB)

CHARACTER (LEN=*) :: CDN
REAL (KIND=JPRB) :: PA (:,:), PB (:,:)

INTEGER :: I1, I2

PRINT *, CDN

DO I2 = 1, SIZE (PA, 2)
DO I1 = 1, SIZE (PA, 1)
  IF (PA (I1, I2) /= PB (I1, I2)) THEN
    WRITE (*, '(2I6," ",3E30.20)') I1, I2, PA (I1, I2), PB (I1, I2), PA (I1, I2) - PB (I1, I2)
  ENDIF
ENDDO
ENDDO

END SUBROUTINE

SUBROUTINE DIFFR3 (CDN, PA, PB)

CHARACTER (LEN=*) :: CDN
REAL (KIND=JPRB) :: PA (:,:,:), PB (:,:,:)

INTEGER :: I1, I2, I3

PRINT *, CDN

DO I3 = 1, SIZE (PA, 3)
DO I2 = 1, SIZE (PA, 2)
DO I1 = 1, SIZE (PA, 1)
  IF (PA (I1, I2, I3) /= PB (I1, I2, I3)) THEN
    WRITE (*, '(3I6," ",3E30.20)') I1, I2, I3, PA (I1, I2, I3), PB (I1, I2, I3), PA (I1, I2, I3) - PB (I1, I2, I3)
  ENDIF
ENDDO
ENDDO
ENDDO

END SUBROUTINE

SUBROUTINE DIFFI1 (CDN, KA, KB)

CHARACTER (LEN=*) :: CDN
INTEGER (KIND=JPIM) :: KA (:), KB (:)

INTEGER :: I1

PRINT *, CDN

DO I1 = 1, SIZE (KA)
  IF (KA (I1) /= KB (I1)) THEN
    WRITE (*, '(I6," ",3I30)') I1, KA (I1), KB (I1), KA (I1) - KB (I1)
  ENDIF
ENDDO

END SUBROUTINE

SUBROUTINE DIFFL1 (CDN, LDA, LDB)

CHARACTER (LEN=*) :: CDN
LOGICAL :: LDA (:), LDB (:)

INTEGER :: I1

PRINT *, CDN

DO I1 = 1, SIZE (LDA)
  IF (LDA (I1) /= LDB (I1)) THEN
    WRITE (*, '(I6," ",2L30)') I1, LDA (I1), LDB (I1)
  ENDIF
ENDDO

END SUBROUTINE

END 

