SUBROUTINE WRAP_CUCALLN_MF    (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN,           &
& YDML_PHY_EC, YGFL,   KIDIA, KFDIA, KLON, KSMAX, KLEV, PDX, KSPPN2D,   LDLAND, LDSLPHY,   PTSPHY,   &
& PVDIFTS,   PTM1, PQM1, PUM1, PVM1, PLITOT,   PVERVEL, PQHFL, PAHFS, PAPHM1,   PAP, PAPH, PGEO,     &
& PGEOH, PGAW,   PCUCONVCA, PGP2DSPP,   PTENT, PTENQ, PTENU, PTENV, PARPRC,   KTOPC, KBASEC, KTYPE,  &
&   KCBOT, KCTOP, KBOTSC, LDCUM, LDSC,   LDSHCV,   PLCRIT_AER,   PLU, PLUDE, PLUDELI, PSNDE, PMFU,   &
& PMFD,   PDIFCQ, PDIFCS, PFHPCL, PFHPCN,   PFPLCL, PFPLCN, PLRAIN, PRSUD,   PSTRCU, PSTRCV, PFCQLF, &
& PFCQIF,   PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWMEAN, PDISS,   KTRAC, PCM1, PTENC, PSCAV )  

USE MODEL_PHYSICS_ECMWF_MOD      , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD                       , ONLY : TERAD
USE YOM_YGFL                     , ONLY : TYPE_GFLD
USE PARKIND1                     , ONLY : JPIM     ,JPRB
USE YOMHOOK                      , ONLY : LHOOK,   DR_HOOK

USE YOMCST                       , ONLY : TCST  
USE YOETHF                       , ONLY : TTHF 

USE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD
USE UTIL_TERAD_MOD
USE UTIL_TYPE_GFLD_MOD
USE UTIL_TCST_MOD
USE UTIL_TTHF_MOD

USE YOMIBL
USE YOMMP0

IMPLICIT NONE


REAL(KIND=JPRB)   ,INTENT(IN)    :: PPLDARE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PPLRG
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTEP
TYPE(TTHF)                         ,INTENT(IN) :: YDTHF
TYPE(TCST)                         ,INTENT(IN) :: YDCST
TYPE(TERAD)                        ,INTENT(IN) :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE)     ,INTENT(IN) :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(IN) :: YDML_PHY_SLIN
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSMAX 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSPPN2D
INTEGER(KIND=JPIM),INTENT(IN)    :: KTRAC 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
LOGICAL           ,INTENT(IN)    :: LDLAND(KLON) 
LOGICAL           ,INTENT(IN)    :: LDSLPHY 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSPHY 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVDIFTS
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLCRIT_AER(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCM1(KLON,KLEV,KTRAC) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLITOT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVERVEL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQHFL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAHFS(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHM1(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPH(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGEO(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGEOH(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENV(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGAW(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCUCONVCA(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGP2DSPP(KLON,KSPPN2D)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSCAV(KTRAC) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDX(KLON)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PARPRC(KLON) 
INTEGER(KIND=JPIM),INTENT(OUT)   :: KTOPC(KLON) 
INTEGER(KIND=JPIM),INTENT(OUT)   :: KBASEC(KLON) 
INTEGER(KIND=JPIM),INTENT(OUT)   :: KTYPE(KLON) 
INTEGER(KIND=JPIM),INTENT(OUT)   :: KCBOT(KLON) 
INTEGER(KIND=JPIM),INTENT(OUT)   :: KCTOP(KLON) 
INTEGER(KIND=JPIM),INTENT(OUT)   :: KBOTSC(KLON) 
LOGICAL           ,INTENT(OUT)   :: LDCUM(KLON) 
LOGICAL           ,INTENT(OUT)   :: LDSC(KLON) 
LOGICAL           ,INTENT(IN)    :: LDSHCV(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLU(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLUDE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLUDELI(KLON,KLEV,4) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSNDE(KLON,KLEV,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PMFU(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PMFD(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDIFCQ(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDIFCS(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFHPCL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFHPCN(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFPLCL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFPLCN(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLRAIN(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PRSUD(KLON,KLEV,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSTRCU(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSTRCV(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFCQLF(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFCQIF(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PMFUDE_RATE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PMFDDE_RATE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCAPE(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PWMEAN(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDISS(KLON,KLEV)

#include "cucalln_mf.intfb.h"

INTEGER (KIND=JPIM) :: ILUN
CHARACTER*18 :: CLBLOCK
LOGICAL :: LLWRITE

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('WRAP_CUCALLN_MF',0,ZHOOK_HANDLE)

ILUN = 70 + IBLOCK
WRITE (CLBLOCK, '(".",I8.8,".",I8.8)') IBLOCK, MYPROC
LLWRITE = MYPROC == 1 .AND. KSTEP == 5

IF (LLWRITE) THEN

OPEN (ILUN, FILE="CUCALLN_MF.CONST"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="NEW")
CALL SAVE (ILUN, YDTHF)
CALL SAVE (ILUN, YDCST)
CALL SAVE (ILUN, YDERAD)
CALL SAVE (ILUN, YDML_PHY_EC)
CALL SAVE (ILUN, YDML_PHY_SLIN)
CALL SAVE (ILUN, YGFL)
CLOSE (ILUN)

OPEN (ILUN, FILE="CUCALLN_MF.DIMS"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="NEW")
WRITE (ILUN) PPLDARE
WRITE (ILUN) PPLRG
WRITE (ILUN) KSTEP
WRITE (ILUN) KLON 
WRITE (ILUN) KSMAX 
WRITE (ILUN) KLEV 
WRITE (ILUN) KSPPN2D
WRITE (ILUN) KTRAC 
WRITE (ILUN) KIDIA 
WRITE (ILUN) KFDIA 
WRITE (ILUN) LDSLPHY 
WRITE (ILUN) PTSPHY 
WRITE (ILUN) PVDIFTS
WRITE (ILUN) PSCAV
CLOSE (ILUN)

OPEN (ILUN, FILE="CUCALLN_MF.IN"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="NEW")
WRITE (ILUN) LDLAND
WRITE (ILUN) PLCRIT_AER
WRITE (ILUN) PTM1
WRITE (ILUN) PQM1
WRITE (ILUN) PUM1
WRITE (ILUN) PVM1
WRITE (ILUN) PCM1
WRITE (ILUN) PLITOT
WRITE (ILUN) PVERVEL
WRITE (ILUN) PQHFL
WRITE (ILUN) PAHFS
WRITE (ILUN) PAPHM1
WRITE (ILUN) PAP
WRITE (ILUN) PAPH
WRITE (ILUN) PGEO
WRITE (ILUN) PGEOH
WRITE (ILUN) PTENT
WRITE (ILUN) PTENQ
WRITE (ILUN) PTENU
WRITE (ILUN) PTENV
WRITE (ILUN) PGAW
WRITE (ILUN) PCUCONVCA
WRITE (ILUN) PGP2DSPP
WRITE (ILUN) PDX
WRITE (ILUN) PTENC
WRITE (ILUN) LDSHCV
CLOSE (ILUN)

ENDIF

CALL CUCALLN_MF    (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN,  YDML_PHY_EC, YGFL,   &
& KIDIA, KFDIA, KLON, KSMAX, KLEV, PDX, KSPPN2D, LDLAND, LDSLPHY, PTSPHY,  PVDIFTS, PTM1, PQM1, PUM1, &
& PVM1, PLITOT, PVERVEL, PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO,  PGEOH, PGAW, PCUCONVCA, PGP2DSPP,    &
& PTENT, PTENQ, PTENU, PTENV, PARPRC, KTOPC, KBASEC, KTYPE,    KCBOT, KCTOP, KBOTSC, LDCUM, LDSC,     &
& LDSHCV, PLCRIT_AER, PLU, PLUDE, PLUDELI, PSNDE, PMFU,  PMFD, PDIFCQ, PDIFCS, PFHPCL, PFHPCN,        &
& PFPLCL, PFPLCN, PLRAIN, PRSUD, PSTRCU, PSTRCV, PFCQLF,  PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE,    &
& PWMEAN, PDISS, KTRAC, PCM1, PTENC, PSCAV )  

IF (LLWRITE) THEN

OPEN (ILUN, FILE="CUCALLN_MF.OUT"//TRIM(CLBLOCK)//".dat", FORM="UNFORMATTED", STATUS="NEW")
WRITE (ILUN) PTENT
WRITE (ILUN) PTENQ
WRITE (ILUN) PTENU
WRITE (ILUN) PTENV
WRITE (ILUN) PTENC
WRITE (ILUN) PARPRC
WRITE (ILUN) KTOPC
WRITE (ILUN) KBASEC
WRITE (ILUN) KTYPE
WRITE (ILUN) KCBOT
WRITE (ILUN) KCTOP
WRITE (ILUN) KBOTSC
WRITE (ILUN) LDCUM
WRITE (ILUN) LDSC
WRITE (ILUN) PLU
WRITE (ILUN) PLUDE
WRITE (ILUN) PLUDELI
WRITE (ILUN) PSNDE
WRITE (ILUN) PMFU
WRITE (ILUN) PMFD
WRITE (ILUN) PDIFCQ
WRITE (ILUN) PDIFCS
WRITE (ILUN) PFHPCL
WRITE (ILUN) PFHPCN
WRITE (ILUN) PFPLCL
WRITE (ILUN) PFPLCN
WRITE (ILUN) PLRAIN
WRITE (ILUN) PRSUD
WRITE (ILUN) PSTRCU
WRITE (ILUN) PSTRCV
WRITE (ILUN) PFCQLF
WRITE (ILUN) PFCQIF
WRITE (ILUN) PMFUDE_RATE
WRITE (ILUN) PMFDDE_RATE
WRITE (ILUN) PCAPE
WRITE (ILUN) PWMEAN
WRITE (ILUN) PDISS
CLOSE (ILUN)

ENDIF

IF (LHOOK) CALL DR_HOOK('WRAP_CUCALLN_MF',1,ZHOOK_HANDLE)

END SUBROUTINE WRAP_CUCALLN_MF

