
SUBROUTINE CUASCN_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, YDECLDP, YDECUMF, YGFL, KIDIA, KFDIA&
&, KLON, KLEV, KSPPN2D, LDTDKMF, PTSPHY, PTENH, PQENH, PUEN, PVEN, PTEN, PQEN, PQSEN, PLITOT&
&, PGEO, PGEOH, PAP, PAPH, PVERVEL, PWUBASE, PGP2DSPP, LDLAND, LDCUM, KTYPE, KLAB, PTU, PQU&
&, PLU, PLRAIN, PMFU, PMFUB, PLGLAC, PMFUS, PMFUQ, PMFUL, PLUDE, PLUDELI, PDMFUP, PLCRIT_AER&
&, PDMFEN, KCBOT, KCTOP, KCTOP0, KDPL, PMFUDE_RATE, PKINEU, PWMEAN, YDSTACK)
!$acc routine (CUASCN_SINGLE_COLUMN) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHLI,ONLY:TEPHLI
USE YOECLDP,ONLY:TECLDP
USE YOM_YGFL,ONLY:TYPE_GFLD
USE SPP_MOD,ONLY:YSPP_CONFIG, YSPP
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECLDP), INTENT (IN)::YDECLDP
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
TYPE (TYPE_GFLD), INTENT (IN)::YGFL
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KSPPN2D
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PTSPHY
REAL (KIND=JPRB), INTENT (IN)::PLCRIT_AER (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PLITOT (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PVERVEL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PWUBASE (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, KSPPN2D)
LOGICAL, INTENT (IN)::LDLAND (KLON)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (IN)::LDTDKMF
INTEGER (KIND=JPIM), INTENT (INOUT)::KTYPE (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KLAB (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLRAIN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFUB (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PLGLAC (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFUL (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLUDELI (KLON, KLEV, 2)
REAL (KIND=JPRB), INTENT (OUT)::PDMFUP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFEN (KLON, KLEV)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCTOP0 (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KDPL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PMFUDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKINEU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWMEAN (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)::ZLUOLD 
temp (REAL (KIND=JPRB), ZBUO, (KLON, KLEV))
REAL (KIND=JPRB)::ZPRECIP 
REAL (KIND=JPRB)::ZQOLD 
temp (REAL (KIND=JPRB), ZDMFDE, (KLON))
temp (REAL (KIND=JPRB), ZDMFEN, (KLON))
REAL (KIND=JPRB)::ZDPMEAN 

temp (REAL (KIND=JPRB), ZPH, (KLON))
REAL (KIND=JPRB)::ZOENTR 

LOGICAL::LLO3
LOGICAL::LLO1 
LOGICAL::LLFLAGUV 
temp (LOGICAL, LLSCVFLAG, (KLON))
temp (LOGICAL, LLFLAG, (KLON))

INTEGER (KIND=JPIM)::IKB
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IK

INTEGER (KIND=JPIM)::JLX 
INTEGER (KIND=JPIM)::JLM
INTEGER (KIND=JPIM)::JLL

INTEGER (KIND=JPIM)::IPRPRCON
INTEGER (KIND=JPIM)::IPENTSHALP
INTEGER (KIND=JPIM)::IPENTRORG

REAL (KIND=JPRB)::ZGLAC
REAL (KIND=JPRB)::ZOCUDET
REAL (KIND=JPRB)::ZZCO
REAL (KIND=JPRB)::ZWU
REAL (KIND=JPRB)::ZVW
REAL (KIND=JPRB)::ZVV
REAL (KIND=JPRB)::ZVI
REAL (KIND=JPRB)::ZSEEN
REAL (KIND=JPRB)::ZSCDE
REAL (KIND=JPRB)::ZROLD
REAL (KIND=JPRB)::ZRNEW
REAL (KIND=JPRB)::ZQUDE
REAL (KIND=JPRB)::ZQEEN
REAL (KIND=JPRB)::ZPRCON
REAL (KIND=JPRB)::ZPRCDGW
REAL (KIND=JPRB)::ZOEALFAP
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZMFUSK
REAL (KIND=JPRB)::ZMFUQK
REAL (KIND=JPRB)::ZMFUN
REAL (KIND=JPRB)::ZMFULK
REAL (KIND=JPRB)::ZMFTEST
REAL (KIND=JPRB)::ZMFMAX
REAL (KIND=JPRB)::ZLNEW
REAL (KIND=JPRB)::ZLEEN
REAL (KIND=JPRB)::ZLCRIT
REAL (KIND=JPRB)::ZKEDKE
REAL (KIND=JPRB)::ZINT
REAL (KIND=JPRB)::ZFACBUO
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZDT
REAL (KIND=JPRB)::ZORCPD
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZDNOPRC
REAL (KIND=JPRB)::ZDKEN
REAL (KIND=JPRB)::ZDKBUO
REAL (KIND=JPRB)::ZDFI
REAL (KIND=JPRB)::ZD
REAL (KIND=JPRB)::ZCONS2
REAL (KIND=JPRB)::ZCBF
REAL (KIND=JPRB)::ZC
REAL (KIND=JPRB)::ZBUOC
REAL (KIND=JPRB)::ZBE
REAL (KIND=JPRB)::ZBC
REAL (KIND=JPRB)::ZALFAW
REAL (KIND=JPRB)::Z_CWIFRAC
REAL (KIND=JPRB)::Z_CWDRAG
REAL (KIND=JPRB)::Z_CPRC2
REAL (KIND=JPRB)::Z_CLDMAX

REAL (KIND=JPRB)::ZMUC
REAL (KIND=JPRB)::ZMUSH
REAL (KIND=JPRB)::ZMU
REAL (KIND=JPRB)::ZXPRCDGW
REAL (KIND=JPRB)::ZXENTSHALP
REAL (KIND=JPRB)::ZXENTRORG

REAL (KIND=JPRB)::ZXE
REAL (KIND=JPRB)::ZXS
REAL (KIND=JPRB)::ZCHANGE

LOGICAL::LLKLAB 
#include "cuadjtq_single_column.intfb.h"
#include "cubasmcn_single_column.intfb.h"
#include "cuentr_single_column.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK

alloc (ZBUO)
alloc (ZDMFDE)
alloc (ZDMFEN)
alloc (ZPH)
alloc (LLSCVFLAG)
alloc (LLFLAG)



JLON = KIDIA


ZCONS2=YDECUMF%RMFCFL/(YDCST%RG*PTSPHY)
ZRG=1.0_JPRB/YDCST%RG
ZORCPD=1.0_JPRB/YDCST%RCPD
ZFACBUO=0.5_JPRB/(1.0_JPRB+0.5_JPRB)
ZPRCDGW=YDECUMF%RPRCON/YDCST%RG
Z_CLDMAX=5.E-3_JPRB
Z_CWIFRAC=0.5_JPRB
Z_CPRC2=0.5_JPRB
Z_CWDRAG=(3._JPRB/8._JPRB)*0.506_JPRB/0.2_JPRB

IF (YDECUMF%LMFGLAC) THEN
  ZGLAC=1.0_JPRB
ELSE
  ZGLAC=0.0_JPRB
ENDIF

LLO3=.FALSE.

ZLUOLD =0.0_JPRB

IF (.NOT.LDCUM (JLON)) THEN
  KCBOT (JLON)=-1
  PMFUB (JLON)=0.0_JPRB
  PQU (JLON, KLEV)=0.0_JPRB
  KTYPE (JLON)=0
ENDIF

PWMEAN (JLON)=0.0_JPRB
ZDPMEAN =0.0_JPRB
ZOENTR =0.0_JPRB
LLSCVFLAG (JLON)=.FALSE.

IF (KTYPE (JLON)>1.AND.YDECUMF%LSCVLIQ)  THEN
    LLSCVFLAG (JLON)=.TRUE.
ENDIF




LLKLAB =.FALSE.

IF (.NOT.LDCUM (JLON).OR.KTYPE (JLON)==3)  THEN
    LLKLAB =.TRUE.
ENDIF



DO JK=1, KLEV

  

  IF (JK/=KCBOT (JLON)) THEN
    PLU (JLON, JK)=0.0_JPRB
  ENDIF

  PKINEU (JLON, JK)=0.0_JPRB
  
  
  PMFU (JLON, JK)=0.0_JPRB
  PMFUS (JLON, JK)=0.0_JPRB
  PMFUQ (JLON, JK)=0.0_JPRB
  PMFUL (JLON, JK)=0.0_JPRB
  
  
  PLUDE (JLON, JK)=0.0_JPRB
  PLUDELI (JLON, JK, 1)=0.0_JPRB
  PLUDELI (JLON, JK, 2)=0.0_JPRB
  PLGLAC (JLON, JK)=0.0_JPRB
  PDMFUP (JLON, JK)=0.0_JPRB
  PLRAIN (JLON, JK)=0.0_JPRB
  
  
  ZBUO (JLON, JK)=0.0_JPRB

  IF (LLKLAB )  THEN
      KLAB (JLON, JK)=0
  ENDIF


  IF (.NOT.LDCUM (JLON).AND.PAPH (JLON, JK)<4.E4_JPRB)  THEN
      KCTOP0 (JLON)=JK
  ENDIF

  PDMFEN (JLON, JK)=0.0_JPRB
  PMFUDE_RATE (JLON, JK)=0.0_JPRB
  
ENDDO



IF (KTYPE (JLON)==3)  THEN
    LDCUM (JLON)=.FALSE.
ENDIF



KCTOP (JLON)=KCBOT (JLON)

IF (LDCUM (JLON)) THEN
  IKB=KCBOT (JLON)
  PKINEU (JLON, IKB)=0.5*PWUBASE (JLON)**2
  PMFU (JLON, IKB)=PMFUB (JLON)
  PMFUS (JLON, IKB)=PMFUB (JLON)*(YDCST%RCPD*PTU (JLON, IKB)+PGEOH (JLON, IKB))
  PMFUQ (JLON, IKB)=PMFUB (JLON)*PQU (JLON, IKB)
  PMFUL (JLON, IKB)=PMFUB (JLON)*PLU (JLON, IKB)
ENDIF



DO JK=KLEV-1, 3,-1
  IK=JK
  CALL CUBASMCN_SINGLE_COLUMN (YDCST, YDECUMF, KIDIA, KFDIA, KLON, KLEV, IK, PTEN&
  &, PQEN, PQSEN, PVERVEL, PGEO, PGEOH, LDCUM, KTYPE, KLAB, KCBOT, PMFU, PMFUB&
  &, PLRAIN, PTU, PQU, PLU, PMFUS, PMFUQ, PMFUL, PDMFUP, YDSTACK=YLSTACK)
  IS=0
  JLM=0
  
  LLFLAG (JLON)=.FALSE.
  ZPRECIP =0.0_JPRB
  LLO1 =.FALSE.
  IS=IS+KLAB (JLON, JK+1)

  IF (KLAB (JLON, JK+1)==0)  THEN
      KLAB (JLON, JK)=0
  ENDIF


  IF ((LDCUM (JLON).AND.KLAB (JLON, JK+1)==2).OR.(KTYPE (JLON)==3.AND.KLAB (JLON, JK+1)==1)) THEN
    LLFLAG (JLON)=.TRUE.
    JLM=JLM+1
    JLX =JLON
  ENDIF


  IF (KLAB (JLON, JK+1)>0) THEN
    LLFLAGUV =.TRUE.
  ELSE
    LLFLAGUV =.FALSE.
  ENDIF

  ZPH (JLON)=PAPH (JLON, JK)

  IF (KTYPE (JLON)==3.AND.JK==KCBOT (JLON)) THEN
    ZMFMAX=(PAPH (JLON, JK)-PAPH (JLON, JK-1))*ZCONS2

    IF (PMFUB (JLON)>ZMFMAX) THEN
      ZFAC=ZMFMAX/PMFUB (JLON)
      PMFU (JLON, JK+1)=PMFU (JLON, JK+1)*ZFAC
      PMFUS (JLON, JK+1)=PMFUS (JLON, JK+1)*ZFAC
      PMFUQ (JLON, JK+1)=PMFUQ (JLON, JK+1)*ZFAC
      PMFUB (JLON)=ZMFMAX
    ENDIF

  ENDIF


  

  IF (IS>0)  THEN
      LLO3=.TRUE.
  ENDIF

  IK=JK
  CALL CUENTR_SINGLE_COLUMN (YDCST, YDECUMF, KIDIA, KFDIA, KLON, KLEV, KSPPN2D, IK, KCBOT, KTYPE&
  &, LDCUM, LLO3, PQSEN, PAPH, PGEOH, PMFU, PGP2DSPP, ZDMFEN, ZDMFDE, YDSTACK=YLSTACK)

  IF (LLO3) THEN
    
    ZQOLD =0.0_JPRB

    

    DO JLL=1, JLM
      JLON=JLX 
      ZDMFDE (JLON)=MIN (ZDMFDE (JLON), 0.75_JPRB*PMFU (JLON, JK+1))

      IF (JK==KCBOT (JLON)) THEN
        
        ZXENTRORG=YDECUMF%ENTRORG
        
        ZOENTR =-ZXENTRORG*(MIN (1.0_JPRB, PQEN (JLON, JK)/PQSEN (JLON, JK&
        &))-YDECUMF%ENTR_RH)*(PGEOH (JLON, JK)-PGEOH (JLON, JK+1))*ZRG
        ZOENTR =MIN (0.4_JPRB, ZOENTR )*PMFU (JLON, JK+1)
      ENDIF


      IF (JK<KCBOT (JLON)) THEN
        ZMFMAX=(PAPH (JLON, JK)-PAPH (JLON, JK-1))*ZCONS2
        ZXS=MAX (PMFU (JLON, JK+1)-ZMFMAX, 0.0_JPRB)
        PWMEAN (JLON)=PWMEAN (JLON)+PKINEU (JLON, JK+1)*(PAP (JLON, JK+1)-PAP (JLON, JK))
        ZDPMEAN =ZDPMEAN +PAP (JLON, JK+1)-PAP (JLON, JK)
        ZDMFEN (JLON)=ZOENTR 

        IF (KTYPE (JLON)>=2) THEN
          
          ZXENTSHALP=YDECUMF%ENTSHALP
          
          ZDMFEN (JLON)=ZXENTSHALP*ZDMFEN (JLON)
          ZDMFDE (JLON)=ZDMFEN (JLON)
        ENDIF

        ZDMFDE (JLON)=ZDMFDE (JLON)*(1.6_JPRB-MIN (1.0_JPRB, PQEN (JLON, JK)/PQSEN (JLON, JK)))
        ZMFTEST=PMFU (JLON, JK+1)+ZDMFEN (JLON)-ZDMFDE (JLON)
        ZCHANGE=MAX (ZMFTEST-ZMFMAX, 0.0_JPRB)
        ZXE=MAX (ZCHANGE-ZXS, 0.0_JPRB)
        ZDMFEN (JLON)=ZDMFEN (JLON)-ZXE
        ZCHANGE=ZCHANGE-ZXE
        ZDMFDE (JLON)=ZDMFDE (JLON)+ZCHANGE
      ENDIF

      PDMFEN (JLON, JK)=ZDMFEN (JLON)-ZDMFDE (JLON)
      PMFU (JLON, JK)=PMFU (JLON, JK+1)+ZDMFEN (JLON)-ZDMFDE (JLON)
      ZQEEN=PQENH (JLON, JK+1)*ZDMFEN (JLON)
      ZSEEN=(YDCST%RCPD*PTENH (JLON, JK+1)+PGEOH (JLON, JK+1))*ZDMFEN (JLON)

      IF (PLITOT (JLON, JK)>YDECLDP%RLMIN) THEN
        ZLEEN=PLITOT (JLON, JK)*ZDMFEN (JLON)
      ELSE
        ZLEEN=0.0_JPRB
      ENDIF

      ZSCDE=(YDCST%RCPD*PTU (JLON, JK+1)+PGEOH (JLON, JK+1))*ZDMFDE (JLON)
      ZQUDE=PQU (JLON, JK+1)*ZDMFDE (JLON)
      PLUDE (JLON, JK)=PLU (JLON, JK+1)*ZDMFDE (JLON)
      ZMFUSK=PMFUS (JLON, JK+1)+ZSEEN-ZSCDE
      ZMFUQK=PMFUQ (JLON, JK+1)+ZQEEN-ZQUDE
      ZMFULK=PMFUL (JLON, JK+1)+ZLEEN-PLUDE (JLON, JK)
      ZFAC=1.0_JPRB/MAX (YDECUMF%RMFCMIN, PMFU (JLON, JK))
      PLU (JLON, JK)=ZMFULK*ZFAC
      PQU (JLON, JK)=ZMFUQK*ZFAC
      PTU (JLON, JK)=(ZMFUSK*ZFAC-PGEOH (JLON, JK))*ZORCPD
      PTU (JLON, JK)=MAX (100._JPRB, PTU (JLON, JK))
      PTU (JLON, JK)=MIN (400._JPRB, PTU (JLON, JK))
      ZQOLD =PQU (JLON, JK)
      PLRAIN (JLON, JK)=PLRAIN (JLON, JK+1)*MAX (0.0_JPRB, PMFU (JLON, JK+1)-ZDMFDE (JLON))*ZFAC
      ZLUOLD =PLU (JLON, JK)
    ENDDO


    

    IF (JK>KDPL (JLON)) THEN
      PTU (JLON, JK)=PTENH (JLON, JK)
      PQU (JLON, JK)=PQENH (JLON, JK)
      PLU (JLON, JK)=0.0_JPRB
      ZLUOLD =PLU (JLON, JK)
    ENDIF

    
    IK=JK

    IF (JLM>0) THEN

      IF (YDECUMF%LSCVLIQ) THEN
        CALL CUADJTQ_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON&
        &, KLEV, IK, ZPH, PTU, PQU, LLFLAG, 6, LLSCVFLAG, YDSTACK=YLSTACK)
      ELSE
        CALL CUADJTQ_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON&
        &, KLEV, IK, ZPH, PTU, PQU, LLFLAG, 1, LLSCVFLAG, YDSTACK=YLSTACK)
      ENDIF

    ENDIF


    IF (YDEPHLI%LPHYLIN) THEN

      DO JLL=1, JLM
        JLON=JLX 

        IF (PQU (JLON, JK)/=ZQOLD ) THEN
          ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTU (JLON, JK)-YDEPHLI%RLPTRC))+1.0_JPRB))
          ZOEALFAP=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTU (JLON, JK+1)-YDEPHLI%RLPTRC))+1.0_JPRB))
          PLGLAC (JLON, JK)=PLU (JLON, JK)*((1.0_JPRB-ZOEALFA)-(1.0_JPRB-ZOEALFAP))
          ZFAC=0.545_JPRB*(TANH (0.17_JPRB*(PTEN (JLON, JK)-YDEPHLI%RLPTRC))+1.0_JPRB)
          PLGLAC (JLON, JK)=PLGLAC (JLON, JK)+ZFAC*PDMFUP (JLON, JK+1)/MAX (YDECUMF%RMFCMIN,&
          & PMFU (JLON, JK+1))*(0.5_JPRB+SIGN (0.5_JPRB, YDCST%RTT-PTEN (JLON, JK)))*ZGLAC
          PTU (JLON, JK)=PTU (JLON, JK)+YDTHF%RALFDCP*PLGLAC (JLON, JK)
        ENDIF

      ENDDO

    ELSE

      DO JLL=1, JLM
        JLON=JLX 

        IF (PQU (JLON, JK)/=ZQOLD ) THEN
          PLGLAC (JLON, JK)=PLU (JLON, JK)*((1.0_JPRB-FOEALFCU (PTU&
          & (JLON, JK)))-(1.0_JPRB-FOEALFCU (PTU (JLON, JK+1))))

          IF (LLSCVFLAG (JLON))  THEN
              PLGLAC (JLON, JK)=0.0_JPRB
          ENDIF

          ZFAC=FOEALFCU (PTEN (JLON, JK))
          PLGLAC (JLON, JK)=PLGLAC (JLON, JK)+ZFAC*PDMFUP (JLON, JK+1)/MAX (YDECUMF%RMFCMIN,&
          & PMFU (JLON, JK+1))*(0.5_JPRB+SIGN (0.5_JPRB, YDCST%RTT-PTEN (JLON, JK)))*ZGLAC
          PTU (JLON, JK)=PTU (JLON, JK)+YDTHF%RALFDCP*PLGLAC (JLON, JK)
        ENDIF

      ENDDO

    ENDIF


    DO JLL=1, JLM
      JLON=JLX 

      IF (PQU (JLON, JK)/=ZQOLD ) THEN
        KLAB (JLON, JK)=2
        PLU (JLON, JK)=PLU (JLON, JK)+ZQOLD -PQU (JLON, JK)
        ZBC=PTU (JLON, JK)*(1.0_JPRB+YDCST%RETV*PQU (JLON, JK)-PLU (JLON, JK+1)-PLRAIN (JLON, JK+1))
        ZBE=PTENH (JLON, JK)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JK))
        ZBUO (JLON, JK)=ZBC-ZBE

        IF (KTYPE (JLON)==3.AND.KLAB (JLON, JK+1)==1) THEN

          IF (ZBUO (JLON, JK)>-0.5_JPRB) THEN
            LDCUM (JLON)=.TRUE.
            KCTOP (JLON)=JK
            PKINEU (JLON, JK)=0.5_JPRB
          ELSE
            KLAB (JLON, JK)=0
            PMFU (JLON, JK)=0.0_JPRB
            PLUDE (JLON, JK)=0.0_JPRB
            PLU (JLON, JK)=0.0_JPRB
          ENDIF

        ENDIF


        IF (KLAB (JLON, JK+1)==2) THEN

          IF (ZBUO (JLON, JK)<-0.1_JPRB) THEN
            PTENH (JLON, JK)=0.5_JPRB*(PTEN (JLON, JK)+PTEN (JLON, JK-1))
            PQENH (JLON, JK)=0.5_JPRB*(PQEN (JLON, JK)+PQEN (JLON, JK-1))
            ZBUO (JLON, JK)=ZBC-PTENH (JLON, JK)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JK))
          ENDIF

          ZBUOC=0.5*(ZBUO (JLON, JK)+ZBUO (JLON, JK+1))/(PTENH &
          &(JLON, JK)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JK)))
          ZDKBUO=(PGEOH (JLON, JK)-PGEOH (JLON, JK+1))*ZFACBUO*ZBUOC

          IF (ZDMFEN (JLON)>0.0_JPRB) THEN
            ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFEN (JLON)/MAX (YDECUMF%RMFCMIN, PMFU (JLON, JK+1)))
          ELSE
            ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFDE (JLON)/MAX (YDECUMF%RMFCMIN, PMFU (JLON, JK+1)))
          ENDIF


          IF (LDTDKMF) THEN
            PKINEU (JLON, JK)=(PKINEU (JLON, JK+1)*(1-ZDKEN)+ZDKBUO)/(1+ZDKEN)
            ZBUOC=ZBUO (JLON, JK)
          ELSE
            PKINEU (JLON, JK)=MAX (-1.E3_JPRB,(PKINEU (JLON, JK+1)*(1-ZDKEN)+ZDKBUO)/(1+ZDKEN))
          ENDIF


          IF (ZBUOC<0.0_JPRB) THEN
            ZKEDKE=PKINEU (JLON, JK)/MAX (1.E-10_JPRB, PKINEU (JLON, JK+1))
            ZKEDKE=MAX (0.0_JPRB, MIN (1.0_JPRB, ZKEDKE))
            ZOCUDET=(1.6_JPRB-MIN (1.0_JPRB, PQEN (JLON, JK)/PQSEN (JLON, JK)))
            ZMFUN=ZOCUDET*SQRT (ZKEDKE)
            ZDMFDE (JLON)=MAX (ZDMFDE (JLON), PMFU (JLON, JK+1)*(1.0_JPRB-ZMFUN))
            PLUDE (JLON, JK)=PLU (JLON, JK+1)*ZDMFDE (JLON)
            PMFU (JLON, JK)=PMFU (JLON, JK+1)+ZDMFEN (JLON)-ZDMFDE (JLON)
          ENDIF


          IF (ZBUO (JLON, JK)>-0.2_JPRB) THEN
            IKB=KCBOT (JLON)
            
            ZXENTRORG=YDECUMF%ENTRORG
            
            ZOENTR =ZXENTRORG*(0.3_JPRB-(MIN (1.0_JPRB, PQEN (JLON, JK-1)/PQSEN (JLON, JK-1))-YDECUMF%ENTR_RH))&
            &*(PGEOH (JLON, JK-1)-PGEOH (JLON, JK))*ZRG*MIN (1.0_JPRB, PQSEN (JLON, JK)/PQSEN (JLON, IKB))**3
            ZOENTR =MIN (0.4_JPRB, ZOENTR )*PMFU (JLON, JK)
          ELSE
            ZOENTR =0.0_JPRB
          ENDIF


          IF (JK>KDPL (JLON)) THEN
            PMFU (JLON, JK)=PMFU (JLON, JK+1)
            PKINEU (JLON, JK)=0.5_JPRB
          ENDIF


          IF (PKINEU (JLON, JK)>0.0_JPRB.AND.PMFU (JLON, JK)>0.0_JPRB) THEN
            KCTOP (JLON)=JK
            LLO1 =.TRUE.
          ELSE
            KLAB (JLON, JK)=0
            PMFU (JLON, JK)=0.0_JPRB
            PKINEU (JLON, JK)=0.0_JPRB
            ZDMFDE (JLON)=PMFU (JLON, JK+1)
            PLUDE (JLON, JK)=PLU (JLON, JK+1)*ZDMFDE (JLON)
          ENDIF


          IF (PMFU (JLON, JK+1)>0.0_JPRB) THEN
            PMFUDE_RATE (JLON, JK)=ZDMFDE (JLON)
          ENDIF

        ENDIF

      ELSEIF (KTYPE (JLON)==2.AND.PQU (JLON, JK)==ZQOLD ) THEN
        KLAB (JLON, JK)=0
        PMFU (JLON, JK)=0.0_JPRB
        PKINEU (JLON, JK)=0.0_JPRB
        ZDMFDE (JLON)=PMFU (JLON, JK+1)
        PLUDE (JLON, JK)=PLU (JLON, JK+1)*ZDMFDE (JLON)
        PMFUDE_RATE (JLON, JK)=ZDMFDE (JLON)
      ENDIF

    ENDDO


    

    IF (LLO1 ) THEN

      IF (LDLAND (JLON).AND.(.NOT.LDTDKMF)) THEN
        ZDNOPRC=5.E-4_JPRB
      ELSE
        ZDNOPRC=3.E-4_JPRB
      ENDIF


      IF (PLU (JLON, JK)>ZDNOPRC) THEN
        ZWU=MIN (15._JPRB, SQRT (2.0_JPRB*MAX (0.1_JPRB, PKINEU (JLON, JK+1))))

        IF (LDTDKMF) THEN
          ZZCO=FOEALFCU (PTU (JLON, JK))*1.3_JPRB+(1.0_JPRB-FOEALFCU (PTU (JLON, JK)))
        ELSE
          ZZCO=1.0_JPRB+0.3_JPRB*FOEALFCU (PTU (JLON, JK))
        ENDIF

        
        ZXPRCDGW=ZPRCDGW
        
        ZPRCON=ZXPRCDGW/(0.75_JPRB*ZWU)*ZZCO
        ZDT=MIN (YDTHF%RTBERCU-YDTHF%RTICECU, MAX (YDTHF%RTBERCU-PTU (JLON, JK), 0.0_JPRB))
        ZCBF=1+Z_CPRC2*SQRT (ZDT)
        ZZCO=ZPRCON*ZCBF

        IF (YGFL%NACTAERO>0) THEN

          IF (YDECLDP%LAERLIQAUTOCP) THEN
            ZALFAW=FOEALFCU (PTU (JLON, JK))
            ZLCRIT=ZALFAW*PLCRIT_AER (JLON, JK)+(1.0_JPRB-ZALFAW)*ZDNOPRC
          ELSEIF (YDECLDP%LAERLIQAUTOCPB) THEN
            ZALFAW=FOEALFCU (PTU (JLON, JK))
            ZLCRIT=ZALFAW*PLCRIT_AER (JLON, KCBOT (JLON))+(1.0_JPRB-ZALFAW)*ZDNOPRC
          ELSE
            ZLCRIT=ZDNOPRC/ZCBF
          ENDIF

        ELSE
          ZLCRIT=ZDNOPRC/ZCBF
        ENDIF

        ZDFI=PGEOH (JLON, JK)-PGEOH (JLON, JK+1)
        ZC=(PLU (JLON, JK)-ZLUOLD )
        ZD=ZZCO*(1.0_JPRB-EXP (-(PLU (JLON, JK)/ZLCRIT)**2))*ZDFI
        ZINT=EXP (-ZD)
        ZLNEW=ZLUOLD *ZINT+ZC/ZD*(1.0_JPRB-ZINT)
        ZLNEW=MAX (0.0_JPRB, MIN (PLU (JLON, JK), ZLNEW))
        ZLNEW=MIN (Z_CLDMAX, ZLNEW)
        ZPRECIP =MAX (0.0_JPRB, ZLUOLD +ZC-ZLNEW)
        PDMFUP (JLON, JK)=ZPRECIP *PMFU (JLON, JK)
        PLRAIN (JLON, JK)=PLRAIN (JLON, JK)+ZPRECIP 
        PLU (JLON, JK)=ZLNEW
      ENDIF

    ENDIF


    

    IF (YDEPHLI%LPHYLIN) THEN

      

      IF (LLO1 ) THEN

        IF (PLRAIN (JLON, JK)>0.0_JPRB) THEN
          ZVW=21.18_JPRB*PLRAIN (JLON, JK)**0.2_JPRB
          ZVI=Z_CWIFRAC*ZVW
          ZALFAW=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(PTU (JLON, JK)-YDEPHLI%RLPTRC))+1.0_JPRB))
          ZVV=ZALFAW*ZVW+(1.0_JPRB-ZALFAW)*ZVI
          ZROLD=PLRAIN (JLON, JK)-ZPRECIP 
          ZC=ZPRECIP 
          ZWU=MIN (15._JPRB, SQRT (2.0_JPRB*MAX (0.1_JPRB, PKINEU (JLON, JK))))
          ZD=ZVV/ZWU
          ZINT=EXP (-ZD)
          ZRNEW=ZROLD*ZINT+ZC/ZD*(1.0_JPRB-ZINT)
          ZRNEW=MAX (0.0_JPRB, MIN (PLRAIN (JLON, JK), ZRNEW))
          PLRAIN (JLON, JK)=ZRNEW
        ENDIF

      ENDIF

    
    ELSE

      

      IF (LLO1 ) THEN

        IF (PLRAIN (JLON, JK)>0.0_JPRB) THEN
          ZVW=21.18_JPRB*PLRAIN (JLON, JK)**0.2_JPRB
          ZVI=Z_CWIFRAC*ZVW
          ZALFAW=FOEALFCU (PTU (JLON, JK))

          IF (LLSCVFLAG (JLON))  THEN
              ZALFAW=1.0_JPRB
          ENDIF

          ZVV=ZALFAW*ZVW+(1.0_JPRB-ZALFAW)*ZVI
          ZROLD=PLRAIN (JLON, JK)-ZPRECIP 
          ZC=ZPRECIP 
          ZWU=MIN (15._JPRB, SQRT (2.0_JPRB*MAX (0.1_JPRB, PKINEU (JLON, JK))))
          ZD=ZVV/ZWU
          ZINT=EXP (-ZD)
          ZRNEW=ZROLD*ZINT+ZC/ZD*(1.0_JPRB-ZINT)
          ZRNEW=MAX (0.0_JPRB, MIN (PLRAIN (JLON, JK), ZRNEW))
          PLRAIN (JLON, JK)=ZRNEW
        ENDIF

      ENDIF

    
    ENDIF


    DO JLL=1, JLM
      JLON=JLX 
      PMFUL (JLON, JK)=PLU (JLON, JK)*PMFU (JLON, JK)
      PMFUS (JLON, JK)=(YDCST%RCPD*PTU (JLON, JK)+PGEOH (JLON, JK))*PMFU (JLON, JK)
      PMFUQ (JLON, JK)=PQU (JLON, JK)*PMFU (JLON, JK)
      ZALFAW=FOEALFCU (PTU (JLON, JK))

      IF (LLSCVFLAG (JLON))  THEN
          ZALFAW=1.0_JPRB
      ENDIF

      PLUDELI (JLON, JK, 1)=ZALFAW*PLUDE (JLON, JK)
      PLUDELI (JLON, JK, 2)=(1.0_JPRB-ZALFAW)*PLUDE (JLON, JK)
    ENDDO

  ENDIF

ENDDO



IF (KCTOP (JLON)==-1)  THEN
    LDCUM (JLON)=.FALSE.
ENDIF

KCBOT (JLON)=MAX (KCBOT (JLON), KCTOP (JLON))

IF (LDCUM (JLON)) THEN
  PWMEAN (JLON)=MAX (1.E-2_JPRB, PWMEAN (JLON)/MAX (1.0_JPRB, ZDPMEAN ))
  PWMEAN (JLON)=SQRT (2.0_JPRB*PWMEAN (JLON))
ENDIF




ENDSUBROUTINE CUASCN_SINGLE_COLUMN

