SUBROUTINE CUBASEN_SINGLE_COLUMN (PPLDARE, PPLRG, YDTHF, YDCST, YDEPHLI, YDECLDP, YDECUMF&
&, KIDIA, KFDIA, KLON, KLEV, KSPPN2D, KINDEX, LDMIXS, LDTDKMF, PTENH, PQENH, PGEOH,&
& PAPH, PQHFL, PAHFS, PGP2DSPP, PKMFL, PTEN, PQEN, PQSEN, PGEO, PTU, PQU, PLU, PWU2H&
&, PWUBASE, KLAB, LDCUM, LDSC, KCBOT, KBOTSC, KCTOP, KDPL, PCAPE, YDSTACK)
!$acc routine (CUBASEN_SINGLE_COLUMN) seq
USE YOEPHLI,ONLY:TEPHLI
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE PARPHY,ONLY:RKAP
USE YOECUMF,ONLY:TECUMF
USE YOECLDP,ONLY:TECLDP
USE YOETHF,ONLY:TTHF
USE SPP_MOD,ONLY:YSPP_CONFIG, YSPP
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

REAL (KIND=JPRB), INTENT (IN)::PPLDARE
REAL (KIND=JPRB), INTENT (IN)::PPLRG
TYPE (TECLDP), INTENT (IN)::YDECLDP
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KSPPN2D
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KINDEX
LOGICAL, INTENT (IN)::LDMIXS
LOGICAL, INTENT (IN)::LDTDKMF
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PQHFL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAHFS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, KSPPN2D)
REAL (KIND=JPRB), INTENT (IN)::PKMFL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PWU2H (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWUBASE (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KLAB (KLON, KLEV)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (OUT)::LDSC (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KBOTSC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KDPL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCAPE (KLON)
TYPE(STACK) :: YDSTACK


 

 
 
 

 
 
 
 
LOGICAL::LLGO_ON (KLON)
 

 




INTEGER (KIND=JPIM)::JKT2
INTEGER (KIND=JPIM)::JKT1
INTEGER (KIND=JPIM)::JKK
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IS





REAL (KIND=JPRB) :: ZSUH (KLON, KLEV)

REAL (KIND=JPRB) :: ZSENH (KLON, KLEV+1)


REAL (KIND=JPRB) :: ZPH (KLON)
REAL (KIND=JPRB)::ZQOLD 
REAL (KIND=JPRB)::ZMIX 
REAL (KIND=JPRB)::ZMIXF (KLON)

 
 

REAL (KIND=JPRB):: ZTU (KLON, KLEV)
REAL (KIND=JPRB):: ZQU (KLON, KLEV)









 


 







REAL (KIND=JPRB)::ZQF
REAL (KIND=JPRB)::ZSF

















REAL (KIND=JPRB)::ZTMP

REAL (KIND=JPRB)::ZRCPD




REAL (KIND=JPRB) ::ZZQENH (KLON, KLEV)
REAL (KIND=JPRB) ::ZZGEOH (KLON, KLEV+1)
REAL (KIND=JPRB) ::ZZAPH (KLON, KLEV+1)



JLON = KIDIA


JKT1=6
JKT2=2


  JKK = 14

 DO JK=JKK-1, JKT2,-1

    IS=0

    IF (JKK==KLEV.OR.KINDEX==KLEV-1) THEN

      IF (LLGO_ON (JLON)) THEN
        ZSUH (JLON, JK)=(ZSUH (JLON, JK+1)*(1.0_JPRB-ZMIX )+2.0_JPRB*ZMIX *ZSF)*ZTMP
        ZQOLD =ZQU (JLON, JK)
        ZTU (JLON, JK)=(ZSUH (JLON, JK)-ZZGEOH (JLON, JK))*ZRCPD
      ENDIF


    ELSE

      IF (JKK==14.AND.JK==12) THEN
        OPEN (77, FILE='fort.77.full', FORM='UNFORMATTED')
        READ (77) KLON
        READ (77) KLEV
        READ (77) ZRCPD
        READ (77) LLGO_ON 
        READ (77) ZZGEOH 
        READ (77) ZZQENH 
        READ (77) ZMIXF 
        READ (77) ZQU 
        READ (77) ZSENH 
        READ (77) ZSUH 
        READ (77) ZZAPH 
        CLOSE (77)
        ZMIX = ZMIXF (6)
      ENDIF


      

      IF (LLGO_ON (JLON)) THEN
        IS=IS+1
        ZMIX =MIN (1.0_JPRB, ZMIX )
        ZQF=(ZZQENH (JLON, JK+1)+ZZQENH (JLON, JK))*0.5_JPRB
        ZSF=(ZSENH (JLON, JK+1)+ZSENH (JLON, JK))*0.5_JPRB
        ZQU (JLON, JK)=ZQU (JLON, JK+1)*(1.0_JPRB-ZMIX )+ZQF*ZMIX 
        ZSUH (JLON, JK)=ZSUH (JLON, JK+1)*(1.0_JPRB-ZMIX )+ZSF*ZMIX 
        ZQOLD =ZQU (JLON, JK)
        ZTU (JLON, JK)=(ZSUH (JLON, JK)-ZZGEOH (JLON, JK))*ZRCPD
        ZPH (JLON)=ZZAPH (JLON, JK)
      ENDIF


      

      IF (JKK==14.AND.JK==12) THEN
        WRITE (*,'(" CUBASE 498 ",E30.20)') ZTU (JLON, JK)
        STOP
      ENDIF

    ENDIF


 ENDDO



ENDSUBROUTINE CUBASEN_SINGLE_COLUMN

