SUBROUTINE CUBASEN_SINGLE_COLUMN (PPLDARE, PPLRG, YDTHF, YDCST, YDEPHLI, YDECLDP, YDECUMF&
&, KIDIA, KFDIA, KLON, KLEV, KSPPN2D, KINDEX, LDMIXS, LDTDKMF, PTENH, PQENH, PGEOH,&
& PAPH, PQHFL, PAHFS, PGP2DSPP, PKMFL, PTEN, PQEN, PQSEN, PGEO, PTU, PQU, PLU, PWU2H&
&, PWUBASE, KLAB, LDCUM, LDSC, KCBOT, KBOTSC, KCTOP, KDPL, PCAPE, YDSTACK)
!$acc routine (CUBASEN_SINGLE_COLUMN) seq
USE YOEPHLI,ONLY:TEPHLI
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE PARPHY,ONLY:RKAP
USE YOECUMF,ONLY:TECUMF
USE YOECLDP,ONLY:TECLDP
USE YOETHF,ONLY:TTHF
USE SPP_MOD,ONLY:YSPP_CONFIG, YSPP
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

REAL (KIND=JPRB), INTENT (IN)::PPLDARE
REAL (KIND=JPRB), INTENT (IN)::PPLRG
TYPE (TECLDP), INTENT (IN)::YDECLDP
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KSPPN2D
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KINDEX
LOGICAL, INTENT (IN)::LDMIXS
LOGICAL, INTENT (IN)::LDTDKMF
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PQHFL (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAHFS (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PGP2DSPP (KLON, KSPPN2D)
REAL (KIND=JPRB), INTENT (IN)::PKMFL (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PLU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PWU2H (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PWUBASE (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KLAB (KLON, KLEV)
LOGICAL, INTENT (INOUT)::LDCUM (KLON)
LOGICAL, INTENT (OUT)::LDSC (KLON)
INTEGER (KIND=JPIM), INTENT (INOUT)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KBOTSC (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KCTOP (KLON)
INTEGER (KIND=JPIM), INTENT (OUT)::KDPL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PCAPE (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

INTEGER (KIND=JPIM)::IDPL 
temp (INTEGER (KIND=JPIM), ILAB, (KLON, KLEV))
INTEGER (KIND=JPIM)::IBOTSC 
INTEGER (KIND=JPIM)::ICBOT 
INTEGER (KIND=JPIM)::ICTOP 

LOGICAL::LLFIRST 
LOGICAL::LLDSC 
LOGICAL::LLDCUM 
LOGICAL::LLDEEP 
temp (LOGICAL, LLGO_ON, (KLON))
LOGICAL::LL_LDBASE 

LOGICAL::LLRESETJL 
LOGICAL::LLRESET

INTEGER (KIND=JPIM)::JKB
INTEGER (KIND=JPIM)::JKT
INTEGER (KIND=JPIM)::JKT2
INTEGER (KIND=JPIM)::JKT1
INTEGER (KIND=JPIM)::JKK
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IK
INTEGER (KIND=JPIM)::IPENTRORG

temp (REAL (KIND=JPRB), ZWU2H, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZBUOH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZSUH, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQENH, (KLON, KLEV+1))
temp (REAL (KIND=JPRB), ZSENH, (KLON, KLEV+1))
temp (REAL (KIND=JPRB), ZS, (KLON, KLEV))

temp (REAL (KIND=JPRB), ZPH, (KLON))
REAL (KIND=JPRB)::ZQOLD 
REAL (KIND=JPRB)::ZMIX 
REAL (KIND=JPRB)::ZMIXF (KLON)

REAL (KIND=JPRB)::ZCBASE 
REAL (KIND=JPRB)::ZDZ 

temp (REAL (KIND=JPRB), ZTU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZQU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZLU, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZCAPE, (KLON, KLEV))
REAL (KIND=JPRB)::ZBUOF
REAL (KIND=JPRB)::ZRHO
REAL (KIND=JPRB)::ZKHVFL
REAL (KIND=JPRB)::ZWS
REAL (KIND=JPRB)::ZUST

REAL (KIND=JPRB)::ZQEXC
REAL (KIND=JPRB)::ZQEX 

REAL (KIND=JPRB)::ZTEXC
REAL (KIND=JPRB)::ZTEX 
REAL (KIND=JPRB)::ZEPS
REAL (KIND=JPRB)::ZTVENH
REAL (KIND=JPRB)::ZTVUH
REAL (KIND=JPRB)::ZLGLAC

REAL (KIND=JPRB)::ZBW
REAL (KIND=JPRB)::ZAW
REAL (KIND=JPRB)::ZQF
REAL (KIND=JPRB)::ZSF
REAL (KIND=JPRB)::ZPDIFFBOT
REAL (KIND=JPRB)::ZPDIFFTOP
REAL (KIND=JPRB)::ZDP
REAL (KIND=JPRB)::ZDTDP
REAL (KIND=JPRB)::ZDQSDT
REAL (KIND=JPRB)::ZESDP
REAL (KIND=JPRB)::ZFAC
REAL (KIND=JPRB)::ZFACI
REAL (KIND=JPRB)::ZFACW
REAL (KIND=JPRB)::ZALFAW
REAL (KIND=JPRB)::ZDQ
REAL (KIND=JPRB)::ZCOR
REAL (KIND=JPRB)::ZQSU

REAL (KIND=JPRB)::ZWORK2
REAL (KIND=JPRB)::ZWORK1

REAL (KIND=JPRB)::ZTMP
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZRCPD

REAL (KIND=JPRB)::ZMU
REAL (KIND=JPRB)::ZXENTRORG

#include "cuadjtq_single_column.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK

alloc (ILAB)
alloc (LLGO_ON)
alloc (ZWU2H)
alloc (ZBUOH)
alloc (ZSUH)
alloc (ZQENH)
alloc (ZSENH)
alloc (ZS)
alloc (ZPH)
alloc (ZTU)
alloc (ZQU)
alloc (ZLU)
alloc (ZCAPE)



JLON = KIDIA
PRINT*," CUBASE 220 ", PCAPE (JLON)


ZAW=1.0_JPRB
ZBW=1.0_JPRB

PWUBASE (JLON)=0.0_JPRB
LLGO_ON (JLON)=.TRUE.
LLFIRST =.TRUE.
KDPL (JLON)=KLEV

JKT1=KINDEX
JKT2=YDECUMF%NJKT2
ZRG=1.0_JPRB/YDCST%RG
ZRCPD=1.0_JPRB/YDCST%RCPD

DO JK=1, KLEV
  
  ZTU (JLON, JK)=PTU (JLON, JK)
  ZQU (JLON, JK)=PQU (JLON, JK)
  ZLU (JLON, JK)=PLU (JLON, JK)
  ILAB (JLON, JK)=KLAB (JLON, JK)
  ZCAPE (JLON, JK)=0.0_JPRB
  
ENDDO

PRINT*," CUBASE 521 ", ZCAPE (JLON, 14)


DO JK=1, KLEV
  
  PWU2H (JLON, JK)=0.0_JPRB
  ZWU2H (JLON, JK)=0.0_JPRB
  ZS (JLON, JK)=YDCST%RCPD*PTEN (JLON, JK)+PGEO (JLON, JK)
  ZQENH (JLON, JK)=PQENH (JLON, JK)
  ZSENH (JLON, JK)=YDCST%RCPD*PTENH (JLON, JK)+PGEOH (JLON, JK)
  
ENDDO


DO JKK=KLEV, JKT1,-1
  IS=0

  

  IF (LLGO_ON (JLON)) THEN
    IS=IS+1
    IDPL =JKK
    ICBOT =JKK
    IBOTSC =KLEV-1
    ICTOP =KLEV-1
    LLDCUM =.FALSE.
    LLDSC =.FALSE.
    LL_LDBASE =.FALSE.
  ENDIF


  

  IF (IS/=0) THEN

    IF (JKK==KLEV) THEN
      ZTEXC=0.2_JPRB
      ZQEXC=1.E-4_JPRB

      

      IF (LLGO_ON (JLON)) THEN
        ZRHO=PAPH (JLON, JKK+1)/(YDCST%RD*(PTEN (JLON, JKK)*(1.0_JPRB+YDCST%RETV*PQEN (JLON, JKK))))
        ZKHVFL=(PAHFS (JLON, JKK+1)*ZRCPD+YDCST%RETV*PTEN (JLON&
        &, JKK)*PQHFL (JLON, JKK+1))/(ZRHO*PPLRG*PPLDARE)
        ZUST=MAX (SQRT (PKMFL (JLON)), 0.1_JPRB)
        ZWS=ZUST**3._JPRB-1.5_JPRB*RKAP*ZKHVFL*(PGEOH (JLON, KLEV)-PGEOH (JLON, KLEV+1))/PTEN (JLON, KLEV)
        ZTEX =0.0_JPRB
        ZQEX =0.0_JPRB

        IF (ZKHVFL<0.0_JPRB) THEN
          ZWS=1.2_JPRB*ZWS**.3333_JPRB
          ILAB (JLON, JKK)=1
          ZTEX =MAX (-1.5_JPRB*PAHFS (JLON, JKK+1)/(ZRHO*ZWS*YDCST%RCPD*PPLRG*PPLDARE), ZTEXC)
          ZQEX =MAX (-1.5_JPRB*PQHFL (JLON, JKK+1)/(ZRHO*ZWS*PPLRG*PPLDARE), ZQEXC)
          ZQU (JLON, JKK)=ZQENH (JLON, JKK)+ZQEX 
          ZSUH (JLON, JKK)=ZSENH (JLON, JKK)+YDCST%RCPD*ZTEX 
          ZTU (JLON, JKK)=(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD+ZTEX 
          ZLU (JLON, JKK)=0.0_JPRB
          ZWU2H (JLON, JKK)=ZWS**2
          PWU2H (JLON, JKK)=ZWU2H (JLON, JKK)
          ZTVENH=(1.0_JPRB+YDCST%RETV*ZQENH (JLON, JKK))*(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD
          ZTVUH=(1.0_JPRB+YDCST%RETV*ZQU (JLON, JKK))*ZTU (JLON, JKK)
          ZBUOH (JLON, JKK)=(ZTVUH-ZTVENH)*YDCST%RG/ZTVENH
        ELSE
          LLGO_ON (JLON)=.FALSE.
        ENDIF

      ENDIF

    
    ELSE

      

      IF (LLGO_ON (JLON)) THEN
        ZRHO=PAPH (JLON, JKK+1)/(YDCST%RD*(PTEN (JLON, JKK)*(1.+YDCST%RETV*PQEN (JLON, JKK))))
        ILAB (JLON, JKK)=1
        ZTEXC=0.2_JPRB
        ZQEXC=1.E-4_JPRB

        IF (JKK==KLEV-1) THEN
          ZTEXC=MAX (ZTEXC, ZTEX )
          ZQEXC=MAX (ZQEXC, ZQEX )

          IF (LDTDKMF) THEN
            ZTEXC=MIN (ZTEXC, 3.0_JPRB)
            ZQEXC=MIN (ZQEXC, 2.E-3_JPRB)
          ELSE
            ZTEXC=MIN (ZTEXC, 1.0_JPRB)
            ZQEXC=MIN (ZQEXC, 5.E-4_JPRB)
          ENDIF

        ENDIF

        ZQU (JLON, JKK)=ZQENH (JLON, JKK)+ZQEXC
        ZSUH (JLON, JKK)=ZSENH (JLON, JKK)+YDCST%RCPD*ZTEXC
        ZTU (JLON, JKK)=(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD+ZTEXC
        ZLU (JLON, JKK)=0.0_JPRB

        IF (PAPH (JLON, KLEV+1)-PAPH (JLON, JKK-1)<60.E2_JPRB) THEN
          ZQU (JLON, JKK)=0.0_JPRB
          ZSUH (JLON, JKK)=0.0_JPRB
          ZWORK1=0.0_JPRB

          DO JK=JKK+1, JKK-1,-1

            IF (ZWORK1<50.E2_JPRB) THEN
              ZWORK2=PAPH (JLON, JK)-PAPH (JLON, JK-1)
              ZWORK1=ZWORK1+ZWORK2
              ZQU (JLON, JKK)=ZQU (JLON, JKK)+ZQENH (JLON, JK)*ZWORK2
              ZSUH (JLON, JKK)=ZSUH (JLON, JKK)+ZSENH (JLON, JK)*ZWORK2
            ENDIF

          ENDDO

          ZQU (JLON, JKK)=ZQU (JLON, JKK)/ZWORK1+ZQEXC
          ZSUH (JLON, JKK)=ZSUH (JLON, JKK)/ZWORK1+YDCST%RCPD*ZTEXC
          ZTU (JLON, JKK)=(ZSUH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD+ZTEXC
        ENDIF

        ZWU2H (JLON, JKK)=1.0_JPRB
        ZTVENH=(1.0_JPRB+YDCST%RETV*ZQENH (JLON, JKK))*(ZSENH (JLON, JKK)-PGEOH (JLON, JKK))*ZRCPD
        ZTVUH=(1.0_JPRB+YDCST%RETV*ZQU (JLON, JKK))*ZTU (JLON, JKK)
        ZBUOH (JLON, JKK)=(ZTVUH-ZTVENH)*YDCST%RG/ZTVENH
      ENDIF

    
    ENDIF

  ENDIF


  DO JK=JKK-1, JKT2,-1
    IS=0

    IF (JKK==KLEV.OR.KINDEX==KLEV-1) THEN
      WRITE (*,*)" CUBASE 409 "

      

      IF (JKK==14.AND.JK==12) THEN
        PRINT*," CUBASE 412 ", LLGO_ON (JLON)
      ENDIF


      IF (LLGO_ON (JLON)) THEN
        IS=IS+1
        ZDZ =(PGEOH (JLON, JK)-PGEOH (JLON, JK+1))*ZRG

        IF (LDTDKMF) THEN
          ZEPS=YDECUMF%ENTSTPC1/((PGEOH (JLON, JK)-PGEOH (JLON, KLEV+1))*ZRG*PPLRG)+YDECUMF%ENTSTPC2
        ELSE
          ZEPS=YDECUMF%ENTSTPC1/((PGEO (JLON, JK)-PGEOH (JLON, KLEV+1))*ZRG*PPLRG)+YDECUMF%ENTSTPC2

          IF (LDMIXS.AND.KINDEX==KLEV.AND.ZLU (JLON, JK+1)>0.0_JPRB)  THEN
              ZEPS=ZEPS*5
          ENDIF

        ENDIF

        ZMIX =0.5_JPRB*ZDZ *PPLRG*ZEPS

        IF (.NOT.LDTDKMF)  THEN
            ZMIX =MIN (1.0_JPRB, ZMIX )
        ENDIF

        ZQF=(PQENH (JLON, JK+1)+PQENH (JLON, JK))*0.5_JPRB
        ZSF=(ZSENH (JLON, JK+1)+ZSENH (JLON, JK))*0.5_JPRB
        ZTMP=1.0_JPRB/(1.0_JPRB+ZMIX )
        ZQU (JLON, JK)=(ZQU (JLON, JK+1)*(1.0_JPRB-ZMIX )+2.0_JPRB*ZMIX *ZQF)*ZTMP
        ZSUH (JLON, JK)=(ZSUH (JLON, JK+1)*(1.0_JPRB-ZMIX )+2.0_JPRB*ZMIX *ZSF)*ZTMP
        ZQOLD =ZQU (JLON, JK)
        ZTU (JLON, JK)=(ZSUH (JLON, JK)-PGEOH (JLON, JK))*ZRCPD
        ZPH (JLON)=PAPH (JLON, JK)
      ENDIF


      

      IF (JKK==14.AND.JK==12) THEN
        WRITE (*,'(" CUBASE 439 ",E30.20)') ZTU (JLON, JK)
      ENDIF

    ELSE
      WRITE (*,*)" CUBASE 443 "
      ZXENTRORG=YDECUMF%ENTRORG

      

      IF (LLGO_ON (JLON)) THEN
        
        ZDZ =(PGEOH (JLON, JK)-PGEOH (JLON, JK+1))*ZRG
        ZMIX =0.4_JPRB*ZXENTRORG*ZDZ *MIN (1.0_JPRB,(PQSEN (JLON, JK)/PQSEN (JLON, KLEV))**3)
      ENDIF


      

      IF (JKK==14.AND.JK==12) THEN
        WRITE (*,'(" CUBASE 457 ",L2)') LLGO_ON (JLON)
        WRITE (*,'(" CUBASE 458 ",E30.20)') PGEOH (JLON, JK)
        WRITE (*,'(" CUBASE 459 ",E30.20)') PQENH (JLON, JK)
        WRITE (*,'(" CUBASE 460 ",E30.20)') PQENH (JLON, JK+1)
        WRITE (*,'(" CUBASE 461 ",E30.20)') ZMIX 
        WRITE (*,'(" CUBASE 462 ",E30.20)') ZQU (JLON, JK)
        WRITE (*,'(" CUBASE 463 ",E30.20)') ZQU (JLON, JK+1)
        WRITE (*,'(" CUBASE 464 ",E30.20)') ZSENH (JLON, JK)
        WRITE (*,'(" CUBASE 465 ",E30.20)') ZSENH (JLON, JK+1)
        WRITE (*,'(" CUBASE 466 ",E30.20)') ZSUH (JLON, JK)
        WRITE (*,'(" CUBASE 467 ",E30.20)') ZSUH (JLON, JK+1)
        WRITE (*,*)" KLON = ", KLON," KLEV = ", KLEV
        OPEN (77, FILE='fort.77.full', FORM='UNFORMATTED')
        READ (77) KLON
        READ (77) KLEV
        READ (77) ZRCPD
        READ (77) LLGO_ON 
        READ (77) PGEOH 
        READ (77) PQENH 
        READ (77) ZMIXF 
        READ (77) ZQU 
        READ (77) ZSENH 
        READ (77) ZSUH 
        READ (77) PAPH 
        CLOSE (77)
        ZMIX = ZMIXF (6)
      ENDIF


      

      IF (LLGO_ON (JLON)) THEN
        IS=IS+1
        ZMIX =MIN (1.0_JPRB, ZMIX )
        ZQF=(PQENH (JLON, JK+1)+PQENH (JLON, JK))*0.5_JPRB
        ZSF=(ZSENH (JLON, JK+1)+ZSENH (JLON, JK))*0.5_JPRB
        ZQU (JLON, JK)=ZQU (JLON, JK+1)*(1.0_JPRB-ZMIX )+ZQF*ZMIX 
        ZSUH (JLON, JK)=ZSUH (JLON, JK+1)*(1.0_JPRB-ZMIX )+ZSF*ZMIX 
        ZQOLD =ZQU (JLON, JK)
        ZTU (JLON, JK)=(ZSUH (JLON, JK)-PGEOH (JLON, JK))*ZRCPD
        ZPH (JLON)=PAPH (JLON, JK)
      ENDIF


      

      IF (JKK==14.AND.JK==12) THEN
        WRITE (*,'(" CUBASE 498 ",E30.20)') ZTU (JLON, JK)
        STOP
      ENDIF

    ENDIF


  ENDDO





ENDDO


ENDSUBROUTINE CUBASEN_SINGLE_COLUMN

