SUBROUTINE CUDDRAFN_SINGLE_COLUMN (YDCST, YDTHF, YDEPHLI, YDECUMF, KIDIA, KFDIA&
&, KLON, KLEV, LDDRAF, PTENH, PQENH, PQSEN, PGEO, PGEOH, PAPH, PRFL, PTD, PQD,&
& PMFU, PMFD, PMFDS, PMFDQ, PDMFDP, PDMFDE, PMFDDE_RATE, PKINED, YDSTACK)
!$acc routine (CUDDRAFN_SINGLE_COLUMN) seq
USE YOEPHLI,ONLY:TEPHLI
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
LOGICAL, INTENT (IN)::LDDRAF (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (INOUT)::PRFL (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PTD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFDP (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFDE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDDE_RATE (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PKINED (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK

REAL (KIND=JPRB)::ZBUOY 
REAL (KIND=JPRB)::ZOENTR 
REAL (KIND=JPRB)::ZCOND 
REAL (KIND=JPRB)::ZDMFDE 
REAL (KIND=JPRB)::ZDMFEN 
temp (REAL (KIND=JPRB), ZPH, (KLON))
temp (LOGICAL, LLO2, (KLON))

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::ITOPDE
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IK

REAL (KIND=JPRB)::ZDKEN
REAL (KIND=JPRB)::ZDKBUO
REAL (KIND=JPRB)::Z_CWDRAG
REAL (KIND=JPRB)::ZFACBUO
REAL (KIND=JPRB)::ZRG
REAL (KIND=JPRB)::ZZENTR
REAL (KIND=JPRB)::ZSEEN
REAL (KIND=JPRB)::ZSDDE
REAL (KIND=JPRB)::ZRAIN
REAL (KIND=JPRB)::ZQEEN
REAL (KIND=JPRB)::ZQDDE
REAL (KIND=JPRB)::ZMFDSK
REAL (KIND=JPRB)::ZMFDQK
REAL (KIND=JPRB)::ZENTR
REAL (KIND=JPRB)::ZDZ
REAL (KIND=JPRB)::ZDMFDP
REAL (KIND=JPRB)::ZBUOYV
REAL (KIND=JPRB)::ZBUOYZ
REAL (KIND=JPRB)::ZBUO

#include "cuadjtq_single_column.intfb.h"

YLSTACK = YDSTACK

alloc (ZPH)
alloc (LLO2)



JLON = KIDIA


ITOPDE=YDECUMF%NJKT3
ZRG=1.0_JPRB/YDCST%RG
ZFACBUO=0.5_JPRB/(1.0_JPRB+0.5_JPRB)
Z_CWDRAG=(3._JPRB/8._JPRB)*0.506_JPRB/0.2_JPRB

ZOENTR =0.0_JPRB
ZBUOY =0.0_JPRB
ZDMFEN =0.0_JPRB
ZDMFDE =0.0_JPRB
PDMFDE (JLON,:)=0.0_JPRB
PMFDDE_RATE (JLON,:)=0.0_JPRB
PKINED (JLON,:)=0.0_JPRB


DO JK=3, KLEV
  IS=0
  
  ZPH (JLON)=PAPH (JLON, JK)
  LLO2 (JLON)=LDDRAF (JLON).AND.PMFD (JLON, JK-1)<0.0_JPRB

  IF (LLO2 (JLON)) THEN
    IS=IS+1
  ENDIF


  

  IF (IS==0)  THEN
      CYCLE
  ENDIF


  

  IF (LLO2 (JLON)) THEN
    ZENTR=YDECUMF%ENTRDD*PMFD (JLON, JK-1)*(PGEOH (JLON, JK-1)-PGEOH (JLON, JK))*ZRG
    ZDMFEN =ZENTR
    ZDMFDE =ZENTR
  ENDIF


  

  IF (JK>ITOPDE) THEN

    

    IF (LLO2 (JLON)) THEN
      ZDMFEN =0.0_JPRB
      ZDMFDE =PMFD (JLON, ITOPDE)*(PAPH (JLON, JK)-PAPH (JLON&
      &, JK-1))/(PAPH (JLON, KLEV+1)-PAPH (JLON, ITOPDE))
    ENDIF

  
  ENDIF


  IF (JK<=ITOPDE) THEN

    

    IF (LLO2 (JLON)) THEN
      ZDZ=-(PGEOH (JLON, JK-1)-PGEOH (JLON, JK))*ZRG
      ZZENTR=ZOENTR *ZDZ*PMFD (JLON, JK-1)
      ZDMFEN =ZDMFEN +ZZENTR
      ZDMFEN =MAX (ZDMFEN , 0.3_JPRB*PMFD (JLON, JK-1))
      ZDMFEN =MAX (ZDMFEN ,-0.75_JPRB*PMFU (JLON, JK)-(PMFD (JLON, JK-1)-ZDMFDE ))
      ZDMFEN =MIN (ZDMFEN , 0.0_JPRB)
    ENDIF

    PDMFDE (JLON, JK)=ZDMFEN -ZDMFDE 
  
  ENDIF


  

  IF (LLO2 (JLON)) THEN
    PMFD (JLON, JK)=PMFD (JLON, JK-1)+ZDMFEN -ZDMFDE 
    ZSEEN=(YDCST%RCPD*PTENH (JLON, JK-1)+PGEOH (JLON, JK-1))*ZDMFEN 
    ZQEEN=PQENH (JLON, JK-1)*ZDMFEN 
    ZSDDE=(YDCST%RCPD*PTD (JLON, JK-1)+PGEOH (JLON, JK-1))*ZDMFDE 
    ZQDDE=PQD (JLON, JK-1)*ZDMFDE 
    ZMFDSK=PMFDS (JLON, JK-1)+ZSEEN-ZSDDE
    ZMFDQK=PMFDQ (JLON, JK-1)+ZQEEN-ZQDDE
    PQD (JLON, JK)=ZMFDQK*(1.0_JPRB/MIN (-YDECUMF%RMFCMIN, PMFD (JLON, JK)))
    PTD (JLON, JK)=(ZMFDSK*(1.0_JPRB/MIN (-YDECUMF%RMFCMIN&
    &, PMFD (JLON, JK)))-PGEOH (JLON, JK))/YDCST%RCPD
    PTD (JLON, JK)=MIN (400._JPRB, PTD (JLON, JK))
    PTD (JLON, JK)=MAX (100._JPRB, PTD (JLON, JK))
    ZCOND =PQD (JLON, JK)
  ENDIF

  
  IK=JK
  CALL CUADJTQ_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA&
  &, KLON, KLEV, IK, ZPH, PTD, PQD, LLO2, 2, YDSTACK=YLSTACK)

  

  IF (LLO2 (JLON)) THEN
    ZCOND =ZCOND -PQD (JLON, JK)
    ZBUO=PTD (JLON, JK)*(1.0_JPRB+YDCST%RETV*PQD (JLON, JK))-PTENH&
    & (JLON, JK)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JK))

    IF (PRFL (JLON)>0.0_JPRB.AND.PMFU (JLON, JK)>0.0_JPRB) THEN
      ZRAIN=PRFL (JLON)/PMFU (JLON, JK)
      ZBUO=ZBUO-PTD (JLON, JK)*ZRAIN
    ENDIF


    IF (ZBUO>=0.0_JPRB.OR.PRFL (JLON)<=(PMFD (JLON, JK)*ZCOND )) THEN
      PMFD (JLON, JK)=0.0_JPRB
      ZBUO=0.0_JPRB
    ENDIF

    PMFDS (JLON, JK)=(YDCST%RCPD*PTD (JLON, JK)+PGEOH (JLON, JK))*PMFD (JLON, JK)
    PMFDQ (JLON, JK)=PQD (JLON, JK)*PMFD (JLON, JK)
    ZDMFDP=-PMFD (JLON, JK)*ZCOND 
    PDMFDP (JLON, JK-1)=ZDMFDP
    PRFL (JLON)=PRFL (JLON)+ZDMFDP
    ZBUOYZ=ZBUO/PTENH (JLON, JK)
    ZBUOYV=ZBUOYZ
    ZBUOYZ=MIN (ZBUOYZ, 0.0_JPRB)
    ZDZ=-(PGEO (JLON, JK-1)-PGEO (JLON, JK))
    ZBUOY =ZBUOY +ZBUOYZ*ZDZ
    ZOENTR =YDCST%RG*ZBUOYZ*0.5_JPRB/(1.0_JPRB+ZBUOY )
    PMFDDE_RATE (JLON, JK)=-ZDMFDE 
    ZDKBUO=ZDZ*ZBUOYV*ZFACBUO

    IF (ZDMFEN <0.0_JPRB) THEN
      ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFEN /MIN (-YDECUMF%RMFCMIN, PMFD (JLON, JK-1)))
    ELSE
      ZDKEN=MIN (1.0_JPRB,(1+Z_CWDRAG)*ZDMFDE /MIN (-YDECUMF%RMFCMIN, PMFD (JLON, JK-1)))
    ENDIF

    PKINED (JLON, JK)=MAX (0.0_JPRB,(PKINED (JLON, JK-1)*(1-ZDKEN)+ZDKBUO)/(1+ZDKEN))
  ENDIF

  
ENDDO



ENDSUBROUTINE CUDDRAFN_SINGLE_COLUMN

