SUBROUTINE CUDLFSN_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, YDECUMF, KIDIA, KFDIA, KLON&
&, KLEV, KCBOT, KCTOP, LDCUM, PTENH, PQENH, PTEN, PQSEN, PGEO, PGEOH, PAPH, PTU, PQU&
&, PMFUB, PRFL, PTD, PQD, PMFD, PMFDS, PMFDQ, PDMFDP, KDTOP, LDDRAF, YDSTACK)
!$acc routine (CUDLFSN_SINGLE_COLUMN) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHLI,ONLY:TEPHLI
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TCST), INTENT (IN)::YDCST
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KCBOT (KLON)
INTEGER (KIND=JPIM), INTENT (IN)::KCTOP (KLON)
LOGICAL, INTENT (IN)::LDCUM (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (IN)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PMFUB (KLON)
REAL (KIND=JPRB), INTENT (INOUT)::PRFL (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PTD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PMFD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDS (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PMFDQ (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PDMFDP (KLON, KLEV)
INTEGER (KIND=JPIM), INTENT (OUT)::KDTOP (KLON)
LOGICAL, INTENT (OUT)::LDDRAF (KLON)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
INTEGER (KIND=JPIM)::IKHSMIN 

REAL (KIND=JPRB)::ZHSMIN 
temp (REAL (KIND=JPRB), ZPH, (KLON))
REAL (KIND=JPRB)::ZCOND 
temp (REAL (KIND=JPRB), ZQENWB, (KLON, KLEV))
temp (REAL (KIND=JPRB), ZTENWB, (KLON, KLEV))
temp (LOGICAL, LLO2, (KLON))

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IS
INTEGER (KIND=JPIM)::IKE
INTEGER (KIND=JPIM)::IK

REAL (KIND=JPRB)::ZTTEST
REAL (KIND=JPRB)::ZTARG
REAL (KIND=JPRB)::ZQTEST
REAL (KIND=JPRB)::ZOELHM
REAL (KIND=JPRB)::ZOEALFA
REAL (KIND=JPRB)::ZMFTOP
REAL (KIND=JPRB)::ZHSK
REAL (KIND=JPRB)::ZBUO

#include "cuadjtq_single_column.intfb.h"
#include "fcttre.func.h"

YLSTACK = YDSTACK

alloc (ZPH)
alloc (ZQENWB)
alloc (ZTENWB)
alloc (LLO2)



JLON = KIDIA



LDDRAF (JLON)=.FALSE.
KDTOP (JLON)=KLEV+1
IKHSMIN =KLEV+1
ZHSMIN =1.E8_JPRB


IF (YDECUMF%LMFDD) THEN

  DO JK=3, KLEV-2

    IF (YDEPHLI%LPHYLIN) THEN
      
      ZTARG=PTEN (JLON, JK)
      ZOEALFA=MIN (1.0_JPRB, 0.545_JPRB*(TANH (0.17_JPRB*(ZTARG-YDEPHLI%RLPTRC))+1.0_JPRB))
      ZOELHM=ZOEALFA*YDCST%RLVTT+(1.0_JPRB-ZOEALFA)*YDCST%RLSTT
      ZHSK=YDCST%RCPD*PTEN (JLON, JK)+PGEO (JLON, JK)+ZOELHM*PQSEN (JLON, JK)

      IF (ZHSK<ZHSMIN ) THEN
        ZHSMIN =ZHSK
        IKHSMIN =JK
      ENDIF

    
    ELSE
      
      ZHSK=YDCST%RCPD*PTEN (JLON, JK)+PGEO (JLON, JK)+FOELHMCU (PTEN (JLON, JK))*PQSEN (JLON, JK)

      IF (ZHSK<ZHSMIN ) THEN
        ZHSMIN =ZHSK
        IKHSMIN =JK
      ENDIF

    
    ENDIF

  ENDDO

  IKE=KLEV-3

  DO JK=3, IKE
    IS=0
    
    ZTENWB (JLON, JK)=PTENH (JLON, JK)
    ZQENWB (JLON, JK)=PQENH (JLON, JK)
    ZPH (JLON)=PAPH (JLON, JK)
    LLO2 (JLON)=LDCUM (JLON).AND.PRFL (JLON)>0.0_JPRB.AND..NOT.LDDRAF (JLON&
    &).AND.(JK<KCBOT (JLON).AND.JK>KCTOP (JLON)).AND.JK>=IKHSMIN 

    IF (LLO2 (JLON)) THEN
      IS=IS+1
    ENDIF


    

    IF (IS==0)  THEN
        CYCLE
    ENDIF

    IK=JK
    CALL CUADJTQ_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON&
    &, KLEV, IK, ZPH, ZTENWB, ZQENWB, LLO2, KCALL=2, YDSTACK=YLSTACK)

    

    IF (LLO2 (JLON)) THEN
      ZTTEST=0.5_JPRB*(PTU (JLON, JK)+ZTENWB (JLON, JK))
      ZQTEST=0.5_JPRB*(PQU (JLON, JK)+ZQENWB (JLON, JK))
      ZBUO=ZTTEST*(1.0_JPRB+YDCST%RETV*ZQTEST)-PTENH (JLON, JK)*(1.0_JPRB+YDCST%RETV*PQENH (JLON, JK))
      ZCOND =PQENH (JLON, JK)-ZQENWB (JLON, JK)
      ZMFTOP=-YDECUMF%RMFDEPS*PMFUB (JLON)

      IF (ZBUO<0.0_JPRB.AND.PRFL (JLON)>10._JPRB*ZMFTOP*ZCOND ) THEN
        KDTOP (JLON)=JK
        LDDRAF (JLON)=.TRUE.
        PTD (JLON, JK)=ZTTEST
        PQD (JLON, JK)=ZQTEST
        PMFD (JLON, JK)=ZMFTOP
        PMFDS (JLON, JK)=PMFD (JLON, JK)*(YDCST%RCPD*PTD (JLON, JK)+PGEOH (JLON, JK))
        PMFDQ (JLON, JK)=PMFD (JLON, JK)*PQD (JLON, JK)
        PDMFDP (JLON, JK-1)=-0.5_JPRB*PMFD (JLON, JK)*ZCOND 
        PRFL (JLON)=PRFL (JLON)+PDMFDP (JLON, JK-1)
      ENDIF

    ENDIF

  
  ENDDO

ENDIF



ENDSUBROUTINE CUDLFSN_SINGLE_COLUMN

