SUBROUTINE CUININ_SINGLE_COLUMN (YDCST, YDTHF, YDEPHLI, YDECUMF, KIDIA, KFDIA&
&, KLON, KLEV, PTEN, PQEN, PQSEN, PUEN, PVEN, PGEO, PAPH, KLAB, PTENH, PQENH&
&, PQSENH, PGEOH, PTU, PQU, PTD, PQD, PUU, PVU, PUD, PVD, PLU, YDSTACK)
!$acc routine (CUININ_SINGLE_COLUMN) seq
USE PARKIND1,ONLY:JPIM, JPRB

USE YOMCST,ONLY:TCST
USE YOETHF,ONLY:TTHF
USE YOECUMF,ONLY:TECUMF
USE YOEPHLI,ONLY:TEPHLI
USE STACK_MOD
#include "stack.h"

IMPLICIT NONE

TYPE (TCST), INTENT (IN)::YDCST
TYPE (TTHF), INTENT (IN)::YDTHF
TYPE (TECUMF), INTENT (IN)::YDECUMF
TYPE (TEPHLI), INTENT (IN)::YDEPHLI
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
REAL (KIND=JPRB), INTENT (IN)::PTEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PUEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PVEN (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEO (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPH (KLON, KLEV+1)
INTEGER (KIND=JPIM), INTENT (OUT)::KLAB (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PTENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (INOUT)::PQSENH (KLON, KLEV)
REAL (KIND=JPRB), INTENT (IN)::PGEOH (KLON, KLEV+1)
REAL (KIND=JPRB), INTENT (OUT)::PTU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PQD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PUU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PVU (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PUD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PVD (KLON, KLEV)
REAL (KIND=JPRB), INTENT (OUT)::PLU (KLON, KLEV)
TYPE(STACK) :: YDSTACK
TYPE(STACK) :: YLSTACK
temp (REAL (KIND=JPRB), ZPH, (KLON))
temp (LOGICAL, LLFLAG, (KLON))

INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IK
REAL (KIND=JPRB)::ZORCPD

#include "cuadjtq_single_column.intfb.h"
#include "cuadjtqs_single_column.intfb.h"

YLSTACK = YDSTACK

alloc (ZPH)
alloc (LLFLAG)



JLON = KIDIA


ZORCPD=1._JPRB/YDCST%RCPD

DO JK=2, KLEV
  
  PTENH (JLON, JK)=(MAX (YDCST%RCPD*PTEN (JLON, JK-1)+PGEO (JLON, JK-1), YDCST&
  &%RCPD*PTEN (JLON, JK)+PGEO (JLON, JK))-PGEOH (JLON, JK))*ZORCPD
  PQENH (JLON, JK)=PQEN (JLON, JK-1)
  PQSENH (JLON, JK)=PQSEN (JLON, JK-1)
  ZPH (JLON)=PAPH (JLON, JK)
  LLFLAG (JLON)=.TRUE.

  

  IF (JK>=KLEV-1.OR.JK<YDECUMF%NJKT2)  THEN
      CYCLE
  ENDIF

  IK=JK

  IF (YDEPHLI%LPHYLIN) THEN
    CALL CUADJTQS_SINGLE_COLUMN (YDTHF, YDCST, KIDIA, KFDIA, KLON,&
    & KLEV, IK, ZPH, PTENH, PQSENH, LLFLAG, 0, YDSTACK=YLSTACK)
  ELSE
    CALL CUADJTQ_SINGLE_COLUMN (YDTHF, YDCST, YDEPHLI, KIDIA, KFDIA, KLON&
    &, KLEV, IK, ZPH, PTENH, PQSENH, LLFLAG, 3, YDSTACK=YLSTACK)
  ENDIF

  
  PQENH (JLON, JK)=MIN (PQEN (JLON, JK-1), PQSEN (JLON, JK-1))+(PQSENH (JLON, JK)-PQSEN (JLON, JK-1))
  PQENH (JLON, JK)=MAX (PQENH (JLON, JK), 0.0_JPRB)
  
ENDDO


PTENH (JLON, KLEV)=(YDCST%RCPD*PTEN (JLON, KLEV)+PGEO (JLON, KLEV)-PGEOH (JLON, KLEV))*ZORCPD
PQENH (JLON, KLEV)=PQEN (JLON, KLEV)
PTENH (JLON, 1)=PTEN (JLON, 1)
PQENH (JLON, 1)=PQEN (JLON, 1)


DO JK=1, KLEV
  IK=JK-1

  IF (JK==1)  THEN
      IK=1
  ENDIF

  
  PTU (JLON, JK)=PTENH (JLON, JK)
  PTD (JLON, JK)=PTENH (JLON, JK)
  PQU (JLON, JK)=PQENH (JLON, JK)
  PQD (JLON, JK)=PQENH (JLON, JK)
  PLU (JLON, JK)=0.0_JPRB
  PUU (JLON, JK)=PUEN (JLON, IK)
  PUD (JLON, JK)=PUEN (JLON, IK)
  PVU (JLON, JK)=PVEN (JLON, IK)
  PVD (JLON, JK)=PVEN (JLON, IK)
  KLAB (JLON, JK)=0
  
ENDDO



ENDSUBROUTINE CUININ_SINGLE_COLUMN

