PROGRAM MAIN

IMPLICIT NONE


INTEGER :: KLEV 
INTEGER :: KLON

INTEGER :: IDUM
LOGICAL, ALLOCATABLE :: LLGO_ON(:)
REAL(KIND=8), ALLOCATABLE :: ZSUH (:,:)
REAL(KIND=8), ALLOCATABLE :: ZSENH(:,:)
REAL(KIND=8), ALLOCATABLE :: ZPH(:)
REAL(KIND=8), ALLOCATABLE :: ZQOLD(:)
REAL(KIND=8), ALLOCATABLE :: ZMIXF(:)
REAL(KIND=8), ALLOCATABLE :: ZTU(:,:)
REAL(KIND=8), ALLOCATABLE :: ZQU(:,:)
REAL(KIND=8), ALLOCATABLE :: ZZQENH(:,:) 
REAL(KIND=8), ALLOCATABLE :: ZZGEOH(:,:) 
REAL(KIND=8), ALLOCATABLE :: ZZAPH(:,:) 

REAL (KIND=8) :: ZQF
REAL (KIND=8) :: ZSF
REAL (KIND=8) :: ZTMP
REAL (KIND=8) :: ZRCPD

INTEGER :: JLON
INTEGER :: JK


KLON = 32
KLEV = 15

ALLOCATE (LLGO_ON(KLON))
ALLOCATE (ZSUH (KLON,KLEV))
ALLOCATE (ZSENH(KLON,KLEV+1))
ALLOCATE (ZPH(KLON))
ALLOCATE (ZQOLD(KLON))
ALLOCATE (ZMIXF(KLON))
ALLOCATE (ZTU(KLON,KLEV))
ALLOCATE (ZQU(KLON,KLEV))
ALLOCATE (ZZQENH(KLON,KLEV))
ALLOCATE (ZZGEOH(KLON,KLEV+1))
ALLOCATE (ZZAPH(KLON,KLEV+1))

JLON = 6

CALL R; CALL TEST0 
CALL R; CALL TEST1 

CONTAINS

SUBROUTINE R
OPEN (77, FILE='fort.77.full', FORM='UNFORMATTED') 
READ (77) IDUM
READ (77) IDUM
READ (77) ZRCPD
READ (77) LLGO_ON(:)
READ (77) ZZGEOH(:,:)
READ (77) ZZQENH(:,:)
READ (77) ZMIXF(:)
READ (77) ZQU(:,:)
READ (77) ZSENH(:,:)
READ (77) ZSUH(:,:)
READ (77) ZZAPH(:,:)
CLOSE (77)
END SUBROUTINE

SUBROUTINE TEST0 

IMPLICIT NONE

DO JK=12, 12
  IF(14==KLEV) THEN 
    ZSUH (JLON,JK)= (ZSUH(JLON,JK+1)*(1.0_8-ZMIXF(JLON))+2.0_8*ZMIXF(JLON)) 
  ELSE
    ZSF = (ZSENH(JLON,JK+1) + ZSENH(JLON,JK))*0.5_8
    ZSUH(JLON,JK)= ZSUH(JLON,JK+1)*(1.0_8-ZMIXF(JLON))+ ZSF*ZMIXF(JLON)
    WRITE (*, '(E30.20)') ZSUH(JLON,JK)
  ENDIF
ENDDO
   

END SUBROUTINE 

SUBROUTINE TEST1 

IMPLICIT NONE

REAL (KIND=8) :: ZMIX 

DO JK=12, 12
  ZMIX = ZMIXF (JLON)
  IF (14==KLEV) THEN
    ZSUH (JLON,JK)= (ZSUH(JLON,JK+1)*(1.0_8-ZMIXF(JLON))+2.0_8*ZMIX) 
  ELSE
    ZSF = (ZSENH(JLON,JK+1) + ZSENH(JLON,JK))*0.5_8
    ZSUH(JLON,JK)= ZSUH(JLON,JK+1)*(1.0_8-ZMIX)+ ZSF*ZMIX
    WRITE (*,'(E30.20)') ZSUH(JLON,JK)
  ENDIF
ENDDO

ENDSUBROUTINE 

END
