PROGRAM MAIN

USE MODEL_PHYSICS_ECMWF_MOD      , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD                       , ONLY : TERAD
USE YOM_YGFL                     , ONLY : TYPE_GFLD
USE PARKIND1                     , ONLY : JPIM     ,JPRB
USE YOMHOOK                      , ONLY : LHOOK,   DR_HOOK

USE YOMCST                       , ONLY : TCST  
USE YOETHF                       , ONLY : TTHF 

USE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD
USE UTIL_TERAD_MOD
USE UTIL_TYPE_GFLD_MOD
USE UTIL_TCST_MOD
USE UTIL_TTHF_MOD

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV
USE STACK_MOD
USE SHUFFLE_MOD
USE DIFF_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT


IMPLICIT NONE


REAL(KIND=JPRB)       :: PPLDARE
REAL(KIND=JPRB)       :: PPLRG
INTEGER(KIND=JPIM)    :: KSTEP

TYPE(TTHF)                          :: YDTHF
TYPE(TCST)                          :: YDCST
TYPE(TERAD)                         :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE)      :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE) :: YDML_PHY_SLIN
TYPE(TYPE_GFLD)                     :: YGFL

INTEGER(KIND=JPIM)    :: KSMAX 
INTEGER(KIND=JPIM)    :: KLEV 
INTEGER(KIND=JPIM)    :: KSPPN2D
INTEGER(KIND=JPIM)    :: KTRAC 
INTEGER(KIND=JPIM)    :: KIDIA 
INTEGER(KIND=JPIM)    :: KFDIA 
LOGICAL               :: LDSLPHY 
REAL(KIND=JPRB)       :: PTSPHY 
REAL(KIND=JPRB)       :: PVDIFTS
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSCAV(:) 

INTEGER(KIND=JPIM), ALLOCATABLE   :: KBASEC(:,:)        
INTEGER(KIND=JPIM), ALLOCATABLE   :: KBOTSC(:,:)        
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCBOT(:,:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KCTOP(:,:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTOPC(:,:)         
INTEGER(KIND=JPIM), ALLOCATABLE   :: KTYPE(:,:)         
LOGICAL           , ALLOCATABLE   :: LDCUM(:,:)         
LOGICAL           , ALLOCATABLE   :: LDLAND(:,:) 
LOGICAL           , ALLOCATABLE   :: LDSC(:,:)          
LOGICAL           , ALLOCATABLE   :: LDSHCV(:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAHFS(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAP(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAPH(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PAPHM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PARPRC(:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCAPE(:,:)         
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCM1(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PCUCONVCA(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCQ(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDIFCS(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDISS(:,:,:)       
REAL(KIND=JPRB)   , ALLOCATABLE   :: PDX(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQIF(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFCQLF(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCL(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFHPCN(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCL(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PFPLCN(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGAW(:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGEO(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGEOH(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PGP2DSPP(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLCRIT_AER(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLITOT(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLRAIN(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLU(:,:,:)         
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDE(:,:,:)       
REAL(KIND=JPRB)   , ALLOCATABLE   :: PLUDELI(:,:,:,:)   
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFD(:,:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFDDE_RATE(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFU(:,:,:)        
REAL(KIND=JPRB)   , ALLOCATABLE   :: PMFUDE_RATE(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PQHFL(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PQM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PRSUD(:,:,:,:)     
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSNDE(:,:,:,:)     
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCU(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PSTRCV(:,:,:)      
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENC(:,:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENQ(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENT(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENU(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTENV(:,:,:)
REAL(KIND=JPRB)   , ALLOCATABLE   :: PTM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PUM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PVERVEL(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PVM1(:,:,:) 
REAL(KIND=JPRB)   , ALLOCATABLE   :: PWMEAN(:,:)        

TYPE (STACK) :: YLSTACK
REAL (KIND=JPRB), ALLOCATABLE :: ZSTACK (:,:)

#include "cucalln_mf.intfb.h"
#include "cucalln_mf_single_column.intfb.h"

INTEGER (KIND=JPIM), PARAMETER :: ILUN = 77
INTEGER (KIND=JPIM) :: JBLK, JLON
INTEGER (KIND=JPIM) :: IOUT
LOGICAL :: LLEXIST

INTEGER (KIND=JPIM) :: NPROMA1, NGPBLKS1, NPROMA, NGPBLKS
INTEGER (KIND=JPIM) :: NTIME, ITIME

INTEGER (KIND=JPIM), POINTER :: IBLOCKLIST1 (:) => NULL ()
INTEGER (KIND=JPIM), TARGET  :: IBLOCKLIST0 (1) = [1_JPIM]

INTEGER (KIND=JPIM), POINTER :: ITASKLIST1 (:) => NULL ()
INTEGER (KIND=JPIM), TARGET  :: ITASKLIST0 (1) = [1_JPIM]

INTEGER (KIND=JPIM) :: ISTACK
INTEGER (KIND=JPIM) :: KLON
LOGICAL :: LLDIFF, LLVERBOSE, LLSINGLECOLUMN
CHARACTER(LEN=256) :: CLOUT, CLCASE, CLCASEREF, CLCASEOUT
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD

CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MAIN_CUCALLN_MF',0,ZHOOK_HANDLE)


CALL INITOPTIONS 

CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CLCASEREF=CLCASE
CALL GETOPTION ("--case-ref", CLCASEREF)
CLCASEOUT = ''
CALL GETOPTION ("--case-out", CLCASEOUT)

ISTACK = 100
CALL GETOPTION ("--stack", ISTACK)

NPROMA = 32
CALL GETOPTION ("--nproma", NPROMA)
NGPBLKS = 1
CALL GETOPTION ("--ngpblks", NGPBLKS)

IBLOCKLIST1 => IBLOCKLIST0
CALL GETOPTION ("--block-list", IBLOCKLIST1)
NGPBLKS1 = SIZE (IBLOCKLIST1)

ITASKLIST1 => ITASKLIST0
CALL GETOPTION ("--task-list", ITASKLIST1)

NTIME = 1
CALL GETOPTION ("--time", NTIME)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--single-column", LLSINGLECOLUMN)

CLOUT = '-'
CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS

KIDIA = 6
KFDIA = 6
KLON = 32
KLEV = 15
IF (LLSINGLECOLUMN) THEN
  CALL TEST1 (KIDIA, KFDIA, KLON, KLEV)
ELSE
  CALL TEST0 (KIDIA, KFDIA, KLON, KLEV)
ENDIF

STOP

END
