SUBROUTINE TEST0 (KIDIA, KFDIA, KLON, KLEV)

IMPLICIT NONE

INTEGER :: KLON 
INTEGER :: KLEV 
INTEGER :: KIDIA 
INTEGER :: KFDIA 

LOGICAL ::         LLGO_ON(KLON)
INTEGER :: JKT2
INTEGER :: JKT1
INTEGER :: JKK
INTEGER :: JL
INTEGER :: JK
INTEGER :: IS
REAL(KIND=8)    :: ZSUH (KLON,KLEV)
REAL(KIND=8)    :: ZSENH(KLON,KLEV+1)
REAL(KIND=8) :: ZPH(KLON)
REAL(KIND=8) :: ZQOLD(KLON)
REAL(KIND=8) :: ZMIX(KLON)
REAL(KIND=8) :: ZTU(KLON,KLEV)
REAL(KIND=8) :: ZQU(KLON,KLEV)
REAL(KIND=8) :: ZQF
REAL(KIND=8) :: ZSF
REAL(KIND=8) :: ZTMP
REAL(KIND=8) :: ZRCPD

REAL(KIND=8)     :: ZZQENH(KLON,KLEV) 
REAL(KIND=8)     :: ZZGEOH(KLON,KLEV+1) 
REAL(KIND=8)     :: ZZAPH(KLON,KLEV+1) 

JKT1=6
JKT2=2

  JKK = 14

 DO JK=JKK-1,JKT2,-1

    IS=0

    IF(JKK==KLEV.OR.6==KLEV-1) THEN 
       DO JL=KIDIA,KFDIA
        IF (LLGO_ON(JL)) THEN
          ZSUH (JL,JK)= (ZSUH(JL,JK+1)*(1.0_8-ZMIX(JL))&
         & +2.0_8*ZMIX(JL)*ZSF) * ZTMP  
          ZQOLD(JL)  = ZQU(JL,JK)
          ZTU (JL,JK) = (ZSUH(JL,JK)-ZZGEOH(JL,JK))*ZRCPD
        ENDIF
      ENDDO

    ELSE

IF (JKK == 14 .AND. JK == 12) THEN
 OPEN (77, FILE='fort.77.full', FORM='UNFORMATTED') 
 READ (77) KLON
 READ (77) KLEV
 READ (77) ZRCPD
 READ (77) LLGO_ON(:)
 READ (77) ZZGEOH(:,:)
 READ (77) ZZQENH(:,:)
 READ (77) ZMIX(:)
 READ (77) ZQU(:,:)
 READ (77) ZSENH(:,:)
 READ (77) ZSUH(:,:)
 READ (77) ZZAPH(:,:)
 CLOSE (77)
ENDIF

      DO JL=KIDIA,KFDIA
        IF (LLGO_ON(JL)) THEN
          IS         = IS+1
          ZMIX(JL)=MIN(1.0_8,ZMIX(JL))
          ZQF = (ZZQENH(JL,JK+1) + ZZQENH(JL,JK))*0.5_8
          ZSF = (ZSENH(JL,JK+1) + ZSENH(JL,JK))*0.5_8
          ZQU(JL,JK)= ZQU(JL,JK+1)*(1.0_8-ZMIX(JL))+ ZQF*ZMIX(JL)
          ZSUH(JL,JK)= ZSUH(JL,JK+1)*(1.0_8-ZMIX(JL))+ ZSF*ZMIX(JL)
          ZQOLD(JL)  = ZQU(JL,JK)
          ZTU (JL,JK)= (ZSUH(JL,JK)-ZZGEOH(JL,JK))*ZRCPD
          ZPH  (JL)  = ZZAPH(JL,JK)
        ENDIF
      ENDDO

IF (JKK == 14 .AND. JK == 12) THEN
 WRITE (*, '(" CUBASE 498 ",E30.20)') ZTU(6,JK)
 STOP
ENDIF

    ENDIF

   
 ENDDO
   

END SUBROUTINE 
