SUBROUTINE TEST1 (KIDIA, KFDIA, KLON, KLEV)

USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KLEV
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA

LOGICAL::LLGO_ON (KLON)
INTEGER (KIND=JPIM)::JKT2
INTEGER (KIND=JPIM)::JKT1
INTEGER (KIND=JPIM)::JKK
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JK
INTEGER (KIND=JPIM)::IS
REAL (KIND=JPRB) :: ZSUH (KLON, KLEV)
REAL (KIND=JPRB) :: ZSENH (KLON, KLEV+1)
REAL (KIND=JPRB) :: ZPH (KLON)
REAL (KIND=JPRB)::ZQOLD 
REAL (KIND=JPRB)::ZMIX 
REAL (KIND=JPRB)::ZMIXF (KLON)
REAL (KIND=JPRB):: ZTU (KLON, KLEV)
REAL (KIND=JPRB):: ZQU (KLON, KLEV)
REAL (KIND=JPRB)::ZQF
REAL (KIND=JPRB)::ZSF
REAL (KIND=JPRB)::ZTMP
REAL (KIND=JPRB)::ZRCPD
REAL (KIND=JPRB) ::ZZQENH (KLON, KLEV)
REAL (KIND=JPRB) ::ZZGEOH (KLON, KLEV+1)
REAL (KIND=JPRB) ::ZZAPH (KLON, KLEV+1)


JLON = KIDIA


JKT1=6
JKT2=2


  JKK = 14

 DO JK=JKK-1, JKT2,-1

    IS=0

    IF (JKK==KLEV.OR.6==KLEV-1) THEN

      IF (LLGO_ON (JLON)) THEN
        ZSUH (JLON, JK)=(ZSUH (JLON, JK+1)*(1.0_JPRB-ZMIX )+2.0_JPRB*ZMIX *ZSF)*ZTMP
        ZQOLD =ZQU (JLON, JK)
        ZTU (JLON, JK)=(ZSUH (JLON, JK)-ZZGEOH (JLON, JK))*ZRCPD
      ENDIF


    ELSE

      IF (JKK==14.AND.JK==12) THEN
        OPEN (77, FILE='fort.77.full', FORM='UNFORMATTED')
        READ (77) KLON
        READ (77) KLEV
        READ (77) ZRCPD
        READ (77) LLGO_ON 
        READ (77) ZZGEOH 
        READ (77) ZZQENH 
        READ (77) ZMIXF 
        READ (77) ZQU 
        READ (77) ZSENH 
        READ (77) ZSUH 
        READ (77) ZZAPH 
        CLOSE (77)
        ZMIX = ZMIXF (6)
      ENDIF


      

      IF (LLGO_ON (JLON)) THEN
        IS=IS+1
        ZMIX =MIN (1.0_JPRB, ZMIX )
        ZQF=(ZZQENH (JLON, JK+1)+ZZQENH (JLON, JK))*0.5_JPRB
        ZSF=(ZSENH (JLON, JK+1)+ZSENH (JLON, JK))*0.5_JPRB
        ZQU (JLON, JK)=ZQU (JLON, JK+1)*(1.0_JPRB-ZMIX )+ZQF*ZMIX 
        ZSUH (JLON, JK)=ZSUH (JLON, JK+1)*(1.0_JPRB-ZMIX )+ZSF*ZMIX 
        ZQOLD =ZQU (JLON, JK)
        ZTU (JLON, JK)=(ZSUH (JLON, JK)-ZZGEOH (JLON, JK))*ZRCPD
        ZPH (JLON)=ZZAPH (JLON, JK)
      ENDIF


      

      IF (JKK==14.AND.JK==12) THEN
        WRITE (*,'(" CUBASE 498 ",E30.20)') ZTU (JLON, JK)
        STOP
      ENDIF

    ENDIF


 ENDDO

ENDSUBROUTINE 

