SUBROUTINE TEST0 (KIDIA, KFDIA, KLON, KLEV)

USE PARKIND1  , ONLY : JPIM, JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM) :: KLON 
INTEGER(KIND=JPIM) :: KLEV 
INTEGER(KIND=JPIM) :: KIDIA 
INTEGER(KIND=JPIM) :: KFDIA 

LOGICAL ::         LLGO_ON(KLON)
INTEGER(KIND=JPIM) :: JKT2
INTEGER(KIND=JPIM) :: JKT1
INTEGER(KIND=JPIM) :: JKK
INTEGER(KIND=JPIM) :: JL
INTEGER(KIND=JPIM) :: JK
INTEGER(KIND=JPIM) :: IS
REAL(KIND=JPRB)    :: ZSUH (KLON,KLEV)
REAL(KIND=JPRB)    :: ZSENH(KLON,KLEV+1)
REAL(KIND=JPRB) :: ZPH(KLON)
REAL(KIND=JPRB) :: ZQOLD(KLON)
REAL(KIND=JPRB) :: ZMIX(KLON)
REAL(KIND=JPRB) :: ZTU(KLON,KLEV)
REAL(KIND=JPRB) :: ZQU(KLON,KLEV)
REAL(KIND=JPRB) :: ZQF
REAL(KIND=JPRB) :: ZSF
REAL(KIND=JPRB) :: ZTMP
REAL(KIND=JPRB) :: ZRCPD

REAL(KIND=JPRB)     :: ZZQENH(KLON,KLEV) 
REAL(KIND=JPRB)     :: ZZGEOH(KLON,KLEV+1) 
REAL(KIND=JPRB)     :: ZZAPH(KLON,KLEV+1) 

JKT1=6
JKT2=2

  JKK = 14

 DO JK=JKK-1,JKT2,-1
  JK = 12
    IS=0

    IF(JKK==KLEV.OR.6==KLEV-1) THEN ! 1/z mixing for shallow
       DO JL=KIDIA,KFDIA
        IF (LLGO_ON(JL)) THEN
          ZSUH (JL,JK)= (ZSUH(JL,JK+1)*(1.0_JPRB-ZMIX(JL))&
         & +2.0_JPRB*ZMIX(JL)*ZSF) * ZTMP  
          ZQOLD(JL)  = ZQU(JL,JK)
          ZTU (JL,JK) = (ZSUH(JL,JK)-ZZGEOH(JL,JK))*ZRCPD
        ENDIF
      ENDDO

    ELSE

IF (JKK == 14 .AND. JK == 12) THEN
 OPEN (77, FILE='fort.77.full', FORM='UNFORMATTED') 
 READ (77) KLON
 READ (77) KLEV
 READ (77) ZRCPD
 READ (77) LLGO_ON(:)
 READ (77) ZZGEOH(:,:)
 READ (77) ZZQENH(:,:)
 READ (77) ZMIX(:)
 READ (77) ZQU(:,:)
 READ (77) ZSENH(:,:)
 READ (77) ZSUH(:,:)
 READ (77) ZZAPH(:,:)
 CLOSE (77)
ENDIF

      DO JL=KIDIA,KFDIA
        IF (LLGO_ON(JL)) THEN
          IS         = IS+1
          ZMIX(JL)=MIN(1.0_JPRB,ZMIX(JL))
          ZQF = (ZZQENH(JL,JK+1) + ZZQENH(JL,JK))*0.5_JPRB
          ZSF = (ZSENH(JL,JK+1) + ZSENH(JL,JK))*0.5_JPRB
          ZQU(JL,JK)= ZQU(JL,JK+1)*(1.0_JPRB-ZMIX(JL))+ ZQF*ZMIX(JL)
          ZSUH(JL,JK)= ZSUH(JL,JK+1)*(1.0_JPRB-ZMIX(JL))+ ZSF*ZMIX(JL)
          ZQOLD(JL)  = ZQU(JL,JK)
          ZTU (JL,JK)= (ZSUH(JL,JK)-ZZGEOH(JL,JK))*ZRCPD
          ZPH  (JL)  = ZZAPH(JL,JK)
        ENDIF
      ENDDO

IF (JKK == 14 .AND. JK == 12) THEN
 WRITE (*, '(" CUBASE 498 ",E30.20)') ZTU(6,JK)
 STOP
ENDIF

    ENDIF

   
 ENDDO
   

END SUBROUTINE 
